apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingress
  namespace: media-server
  labels:
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`jellyfin.{{ .Values.cloudflare_zone }}`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
  tls:
    domains:
    - main: jellyfin.{{ .Values.cloudflare_zone }}
    secretName: {{ .Values.cloudflare_zone_hyphen }}-tls
