---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-certificate
  namespace: default
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cattle-system,media-server"
spec:
  secretName: {{ .Values.cloudflare_zone_hyphen }}-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.{{ .Values.cloudflare_zone }}"
  dnsNames:
  - "{{ .Values.cloudflare_zone }}"
  - "*.{{ .Values.cloudflare_zone }}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cattle-system,media-server"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-domain-certificate
  namespace: default
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kubernetes-dashboard,traefik"
spec:
  secretName: local-{{ .Values.cloudflare_zone_hyphen }}-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.local.{{ .Values.cloudflare_zone }}"
  dnsNames:
  - "local.{{ .Values.cloudflare_zone }}"
  - "*.local.{{ .Values.cloudflare_zone }}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kubernetes-dashboard,traefik"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

