---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    {{ if .Values.enable_production }}server: https://acme-v02.api.letsencrypt.org/directory{{ else }}server: https://acme-staging-v02.api.letsencrypt.org/directory{{ end }}
    email: {{ .Values.lets_encrypt_email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.cloudflare_email }}
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "{{ .Values.cloudflare_zone }}"


