apiVersion: v1
kind: Secret
metadata:
  name: pinchflat-secrets
  namespace: media-server
type: Opaque
stringData:
  auth-username: "username"  # Replace with wanted username
  auth-password: "password"  # Replace with wanted password

