apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchflat
  namespace: media-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pinchflat
  template:
    metadata:
      labels:
        app: pinchflat
    spec:
      containers:
      # WireGuard VPN sidecar with integrated PIA setup
      - name: wireguard
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          echo "Installing dependencies..."
          
          # Set up alternative Alpine mirrors with retry logic
          echo "Setting up alternative Alpine repositories..."
          cat > /etc/apk/repositories << EOF
http://dl-cdn.alpinelinux.org/alpine/v3.22/main
http://dl-cdn.alpinelinux.org/alpine/v3.22/community
http://dl-4.alpinelinux.org/alpine/v3.22/main
http://dl-4.alpinelinux.org/alpine/v3.22/community
http://mirror.ps.kz/alpine/v3.22/main
http://mirror.ps.kz/alpine/v3.22/community
EOF
          
          # Retry package installation with fallback
          for i in {1..3}; do
            echo "Attempt $i/3: Updating package index..."
            if apk update; then
              echo "Package index updated successfully"
              break
            else
              echo "Attempt $i/3 failed, waiting 10s before retry..."
              sleep 10
              if [ $i -eq 3 ]; then
                echo "All attempts failed, trying fallback repositories..."
                cat > /etc/apk/repositories << EOF
http://mirror.ps.kz/alpine/v3.22/main
http://mirror.ps.kz/alpine/v3.22/community
http://dl-4.alpinelinux.org/alpine/v3.22/main
http://dl-4.alpinelinux.org/alpine/v3.22/community
EOF
                apk update || echo "WARNING: Package index update failed, proceeding anyway..."
              fi
            fi
          done
          
          apk add --no-cache curl jq git bash wireguard-tools iptables iproute2 dnsmasq bind-tools
          
          echo "Cloning PIA manual-connections repository..."
          cd /tmp
          git clone https://github.com/MrZeLee/manual-connections.git
          cd manual-connections
          
          echo "Setting up PIA WireGuard connection..."
          
          # Run PIA setup script with environment variables
          export PIA_USER="${PIA_USERNAME}"
          export PIA_PASS="${PIA_PASSWORD}"
          export VPN_PROTOCOL=wireguard
          export DISABLE_IPV6=yes
          export DIP_TOKEN=no
          export AUTOCONNECT=true  # Auto-select best server
          export PIA_PF=false  # Disable port forwarding for Pinchflat
          export PIA_DNS=true
          export PIA_CONNECT=true
          export MAX_LATENCY=0.5
          
          echo "Starting PIA VPN with run_setup.sh..."
          ./run_setup.sh &
          PIA_PID=$!
          
          # Wait for VPN to be fully established
          echo "Waiting for PIA VPN to be ready..."
          while ! wg show pia > /dev/null 2>&1; do
            echo "Waiting for VPN interface pia to be ready..."
            kill -0 $PIA_PID
            sleep 5
          done
          echo "VPN interface ready!"
          
          echo "PIA VPN setup completed, monitoring connection..."
          
          # Monitor VPN connection
          while true; do
            VPN_OK=true
            
            # Check interface exists and is up
            if ! ip link show pia | grep -q "state UP"; then
              echo "ERROR: VPN interface pia is down"
              VPN_OK=false
            fi
            
            # Check default route goes through VPN
            if ! ip route | grep -q "default.*dev pia"; then
              echo "ERROR: Default route not through VPN"
              VPN_OK=false
            fi
            
            # Check VPN gateway is reachable
            VPN_GW=$(ip route | grep "default.*dev pia" | awk '{print $3}')
            if [ -n "$VPN_GW" ] && ! ping -c 1 -W 2 "$VPN_GW" >/dev/null 2>&1; then
              echo "ERROR: VPN gateway $VPN_GW unreachable"
              VPN_OK=false
            fi
            
            if [ "$VPN_OK" = false ]; then
              echo "Restarting VPN..."
              ./run_setup.sh &
              PIA_PID=$!
              sleep 60
            else
              echo "VPN connection healthy"
              sleep 30
            fi
          done
        env:
        - name: PIA_USERNAME
          valueFrom:
            secretKeyRef:
              name: qbittorrent-secrets
              key: pia-username
        - name: PIA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qbittorrent-secrets
              key: pia-password
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check if WireGuard interface is up
              wg show pia > /dev/null 2>&1
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 20  # Allow 5 minutes for VPN setup
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check if WireGuard is running and connected
              wg show pia > /dev/null 2>&1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check if WireGuard is connected
              wg show pia > /dev/null 2>&1
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      
      # Pinchflat container
      # Alternative images if primary is down:
      # - ghcr.io/kieraneglin/pinchflat:latest (GitHub Container Registry)
      - name: pinchflat
        image: keglin/pinchflat:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for VPN interface before starting Pinchflat..."
          # Wait for pia interface to be available for binding
          while ! ip link show pia > /dev/null 2>&1; do
            echo "Waiting for VPN interface pia..."
            sleep 5
          done
          
          echo "VPN interface ready, starting Pinchflat..."
          exec /app/bin/pinchflat start
        ports:
        - containerPort: 8945
          name: webui
          protocol: TCP
        env:
        - name: TZ
          value: "America/New_York"
        - name: PINCHFLAT_HOST
          value: "0.0.0.0"
        - name: PINCHFLAT_PORT
          value: "8945"
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: pinchflat-secrets
              key: auth-username
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pinchflat-secrets
              key: auth-password
        volumeMounts:
        - name: pinchflat-config
          mountPath: /config
        - name: jellyfin-media-shared
          mountPath: /downloads
          subPath: youtube
        startupProbe:
          httpGet:
            path: /
            port: 8945
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12  # Allow 2 minutes for startup
        livenessProbe:
          httpGet:
            path: /
            port: 8945
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8945
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      
      volumes:
      - name: pinchflat-config
        persistentVolumeClaim:
          claimName: pinchflat-config
      - name: jellyfin-media-shared
        persistentVolumeClaim:
          claimName: jellyfin-media
      
      # Containers in same pod automatically share network namespace
      
      # Use cluster DNS initially, VPN will override DNS via iptables rules
      dnsPolicy: ClusterFirst
      restartPolicy: Always
