apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-webui
  namespace: media-server
spec:
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-webui
  namespace: media-server
spec:
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: 8989
    targetPort: 8989
    protocol: TCP
  type: ClusterIP