apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-jellyfin-storage
  resources:
    requests:
      storage: 2500Gi
