apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    meta.helm.sh/release-name: wireguard
  labels:
  name: wireguard
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Lisbon
        - name: PEERS
          value: user1,user2,user3
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: ALLOWEDIPS
          value: 0.0.0.0/0
        - name: SERVERPORT
          value: "51820" 
        - name: SERVERURL
          value: wireguard.{{ .Values.cloudflare_zone }}
        image: linuxserver/wireguard:latest
        name: wireguard
        ports:
        - containerPort: 51820
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        volumeMounts:
        - mountPath: "/config/"
          name: wireguard-config
      # imagePullSecrets:
      # - name: docker-registry
      initContainers:
      - command:
        - sh
        - "-c"
        - ENI=$(ip route get 8.8.8.8 | grep 8.8.8.8 | awk '{print $5}'); sed "s/ENI/$ENI/g"
          /etc/wireguard-secret/wg0.conf.template > /config/wg0.conf; chmod 400 /config/wg0.conf
        - sysctl -w net.ipv4.ip_forward=1
        image: busybox
        name: wireguard-template-replacement
        volumeMounts:
        - mountPath: "/config/"
          name: wireguard-config
        - mountPath: "/etc/wireguard-secret/"
          name: wireguard-secret
      volumes:
      - name: wireguard-config
        persistentVolumeClaim:
          claimName: wireguard-config-pvc
      - name: wireguard-secret
        secret:
          secretName: wireguard
