---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: values-secret
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgAYS9eJca08AjG4B8lcyTidL42s6nFtj/P6M9hJwIrxWkUedn4DH9a9VZ+6MALPRxcnKNI7A+F3MPF3eqPEKYY6vof/doqp5WtyH+ynUCAL1smWZzu0T3CwXMU495onRXYrZuRliiYyxzRhT5iRzQzavQlZrmiR8bRsIY5jUwFXR6Pmkd0uUIeVZQB55lJ9GwAdkft/XTmovtjk0hBKjqQDx5Q3g6TqTypr+udovl1M3vqKZifVV3gDMqL2sM7SuSGf0Yf19NQZKuDv41tmMymdk6lZ/9pI9QPUG3iZTZ1+sxlGAet5osjgV4dmm7UfoDBfAd9s+a4b6zLSMNnlYr6hNtGc5Sg/5NTT4oxFHFR/6Da4dquKh9/e7xi6Sl1K9gCQ6N5AxaRzNqO2aIFw2okbcSBfuKPwkJyF4so5656WoItkbaeSlHhsHlk4PH/NxJM2aQTtd6aG41pkaVZgsuwYYwqHgSJekFJrKhyFEJI30MiDxeX3GdqrdB7gvh5F0mBRCfoGcBNFErBpQ/2d6tdGLJRn4J8uodTK2nLlxIOKpcFIiLoNSkY40HN+eywxedBqQckeaSYsk21thLmdhr2Q+BNsHUI7auHmtiw2LqWJBrO9RBdusxjFI5kT4fUZYL4prfm2OZSqHdfD4qnMYagxDh6P997Bm6zs8+O2ZgvlOYd9Q7TBEsY6OuSlpOVvjC1CPXvSPWu4P2zHOrUyZnXb7+PgnScW2cO26jVBsVZNHti4ASGTbr2rk6PK/qAx0d3TLTmDcS9SeePP9LPIv7Oikrf61hPC3DBXVrDgYfeHkO28aL+WZjqSKGtwJx0PzOq/XsJs1k9VZRdKl5q6HOWbFiJ3fAyH9H4syAfnjp39mATfe43MVmVB5J++buZBPagisW0wY9op6pXZTltzck9mEG3QHe6T
  template:
    metadata:
      creationTimestamp: null
      name: values-secret
      namespace: monitoring
