apiVersion: v1
kind: Secret
metadata:
  name: config
  namespace: cockroachdb
type: Opaque
stringData:
  values.yaml: |
    {
      "proxy": {
        "enabled": false,
        "httpServer": {
          "host": "localhost",
          "port": 1234
        },
        "source": {
          "host": "localhost",
          "port": 5433
        },
        "destination": {
          "host": "localhost",
          "port": 5432
        }
      },
      "postgresApi": {
        "enabled": false,
        "host": "localhost",
        "port": 8000,
        "openApiFilePath": "./cfg/pgOpenApi.yaml",
        "database": {
          "host": "localhost",
          "port": 5432,
          "username": "postgres",
          "password": "admin",
          "databaseName": "database-proxy"
        }
      },
      "cockroachApi": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 8010,
        "openApiFilePath": "./crbOpenApi.yaml",
        "database": {
          "host": "cockroachdb-public.cockroachdb.svc.cluster.local",
          "port": 26257,
          "sslEnabled": true,
          "sslCertPath": "/ca.pem",
          "username": "username",
          "password": "password",
          "databaseName": "defaultdb"
        }
      }
    }
