---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBtBdbc0plmNWixEQRKZzKRr0o960GvYcfausgMZOERwZWv8Oh6r3kG8Opw9y5oc8v+y3GLkSNOcxq1pPi99lTEg0ewEq7DxnX5njnFphlyBS4Uz32whFJOw8BPrH8kLtF6obFn3MJxP8UFSKYe9HChuPoapGEF8ljkS6FZXpVGqNuBo4MK296NVKpfeRdQEAp3yZQ92RKV0zwnD4ZmL7vw0ov8wiftvTxsFojh/s9G7BDHl2PI3FC98TSnnMaJioeN1VnaxtW+UKOqYXpqDzsPUjUgustsrjw0CHuVdiIh+mBwKVdQ9SbIOEKoxcjlyZl5l7xOoT+Qasz6aHwWUccOm67GXvfeZrnPaBvUs85KT+3bz6q5YETuefxryCw22qLeK+AJurCKGxrJG50M2KXBPKklwwz3JEGFOIGpKPRwpXNlUl7SghKMWSETuIT6N4r+LuNhaLQSvbpPClpiQ+UKswXpou+xFxG5HY1cY4rcXv45WcrdH1SYt4Vz46ESYHjc8T7nC5noLKA37A0oB4ldrAZ3AdMg+ZwXLs2j58wStc+0FOXvMZkc90MVIINGf8JdhuQXbFGAMdik8aTG4AuY3kyKyZhRyzE0WfZJSWBM3o7Ozea2CGJ0LoMF2HFWEGsmMCmylv9GfEGBcHTIM2gvzAva3qwZOG1Br3xRyz0BGP6lPSMT0wwCH8qebQ00+99ca4ZN3yc2L8YeTNnRFUIPpNTHSV8VU2SYglp+5UfQz8uFSVr9kVwD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
