---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCP401b69/igE6hbA5c8/awOb2T2es45bYWn8dvNmiJ8GdQyEXVkZMPYv3VnPiZGmNx3PrUq/ePKpD4csK4CJGiwi9FpJ6rxTaZ1Yh/kBY+S8eP3heVVpcVS7ODimMcLysDTpPBp9uPCL9yEqxD3sVTPdj2HqydbIQwHRiw7nbfLIraR2pn66XzGOobLvyxpIkY/H/XIlV4RQr/tRT5kYE7UlYnKAY/+JDSzhhAQULSeBFCqTzDDxtcn4PXoVP1kXPeqBxM1IY6VANg/l+20DvpEphdijydhKEcDTN4uyzEtypWjalsliWy31G2oXsJvq66Sn00Q/418i7UTZJsQB3wRWQNcuXSuuMAo6KaYFPeaxJKXypHlTYjw5Yj3k4EqaiUuxJs26R+SNkBrIErFZrqSA4v40YjX1PLybVvtkAjBquUNFQsYl23ZyR83El+bRK7KFN3tML0J+vKxs9Tet3yC6jYKneRm8DZxGzdLFy8TDCOg079ZYG1CLV04Qak/q2LOytAUfPefRSTy9ybGunfJYEraKAvtJ2C2VmHZ8lftfNXo3MnJFg7uCULEnzojhl2q0QentGeMbSnb9VQAOIuC2xrnYYBGOfYjwHKps64+D7FYoIw7ZZfWX0C1UqqE2Cq04KYJRbmFAOG9+payBlcPB8z2nEckmH9KOKdAf9LkORseBNpOul0Icz74AdWnT2LyfutLEVMafEy7KRZkjWhBXV7wjUO1MlZu0TzSmY+xbVUQGdG5Stt
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
