---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgA0Sdj/zDPXPMxKCplYZFHxpeLiES7llBJZAii5fXEHrdMWdUkE3Zh1YQQ3KYZaBLLaPCrQjSgVf0mei9m8+DH8Oq+HRkM1YZlZ/K8AuW5SeIEht7S39BmNcDlNKjPRSPCs0l7gTZxXfvHX9KvjBIDig6UcFKypkdfmvmo6G4X9k/NTNIyH8AiTshpISoi1GlvXByVoVMcSfm693fTZueA0XhV7+TbwItVXLVy1K3PK+AHPs0RCjhXoO+VYmomEOJP+UdhAC6h/KrOP9WQCTBRTLXMFiqmVNxXTEkeF8Ex+VyNPfV72fN18BzvI4T1hqZhTFvIqk8MtfDcFFDR9q1+oxjpMUjwU0VVdlrpozAUlfRdyFq4oiZoPLiCoat1zNMi6GCVkZwGIlWhkWvAI5rG7AkJtx5FWjdcmZiE0JdIg0bO7n5O8ZdQD2WiLPdlToezbdbxo6+AerVEKC+r5fVoY1AEHEXQuD0N5aoY2LB8vA5AwdfWvnYgGWhv6iDej4x0L2UFG6OyD/H/7r47PixowGrTHmmFBkhp3WPEGIj4HXx6h/9BSigheJg16nqQCB+Lr+CKrASEpIJGcZL966bijeaA2nLjZcvycznEgbYRbkCHzFD8VF4M9nDynyFRnbFM31/2ZLRJV2EBpCos49kqST8FV1JPEpxMC/6XI/ndCVQQJomqvgRtXTgYvY0N4VLJ0IAXTpZ9mE22Nx6yjBsO7fpcTal/mDYrG/wxodvJVsTg3Oj+oTdkL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
