---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAfBhfSHSJ5vRM4X4SRtm/U9+BCB1UerV345TSP+mm7wx6BudQTy4Om5F7zb1V0tDj2fatAhWDiCuYGOwT342SS2fZzr9pymr55P5yTD1jHjgrDSGit8x5zqCk84Vbnu2Jh5DyTrMdJZ3NiWNePHKmDdqD8tpcSMUssEfH9xY9QIw/gCbJe1wptQJsy3c9tVr5QIPJD4ElSGlfq/G/HXiI8VpDeto1MunI123uXe7qzkU10lHQL7KQ+Ww78fAPxSL0jmW7UYLj/sJDOKPZ4lmRA9wywa6zJELQM9CN35GtGJfA65oqhRYai6Capq+ECGhZMLA8W/MTYYyI2rS+JQ/XKp1tNmWQGFTzEPTCx7w2/IVGRNICYG0HPle0e8411wY4+2DpzOmkV9hHMIwlAqzgWbF8j2BRxXUFNB0SbAJ8vkHOhCfEqDw8/3uaL4yZNxnEx6dgXqXyQcN+2MXriL9GQe1Gpy91di1sHHWAeOKkCCYmcpTOjxBMu+hbbkTgAoaAVrSfnBG057TKVWJiCP+QhWsDpPmm//CdC7pZ/MsMidZokqkEF1cQhfbeMKOGqNMK1lyGu0GR7FJsiFyHV1m54sBkYu2E3z5KZZtF0xAPqx2lISn76R0mNux09vrFDmUxxNrHVOj3Zo+TEPd8rk3l8YLYoObhnDSAiG6GS573uHaKReAEtIABEFeHCAw2Pz4xdzTZ8ehCogIazWhrVpkgI2LgyDjfInyiqN2rzmqR0++YtiifGJ5PP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
