---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgB2BH9hvpyQma2kG47foBaa7mY+gU1+7NzE+TUPoW1NVtxtrWtW67GbV3rsZXMY+dQM3mmhr3P1FF2dGtTAd79ZijGODdMOeAPJbSe5qKS5Gq3kzBmaIayuOgLdbk8dee/c7liV0IMFh0xXJVoFkLI3/Kh9SqRH5E+35cqmTKmjLsZm+TnzE6oZ6i8Zdo6c5PNXVdCoCLeWLOqIgjYRJ3eG/DJseTqWU/bENFNPqhdH2mWcWAV60LMYdM90bRplsZalcbhUT9pjYL3yjuvJPZYiEv60j5dE8i46Hc4wc1CXj4uGgxmcBKrVWI6p9zuw7s/OR8mVn1iHSAkmE5emQPrKzELObNDp3rCYV6ccd5axiTMQbwdKjBzK7xhiwN1KlCi5XvOMV+YVFUurNgZScu3PCvtwxzOV2Bx6oy5iXN2x5rII/GBpi4y0G3TBa0YTh843Z7TYnPbSIVsH+jBTh2juLaA0iZF+Ktr+csFSJSAFrvsbDSg6/ERRi7Dm0T7FHCKTiEXfudtSmCaLyDqPcA/zFTTCRMLjDeDxm0oUeRdcM4++DGU+2B6eWHIIguXYNi2ljuN0lHfZAESyRiE582EzBwBKaF2OssYpqrfP0MeWA7g99qecBqFLYbG3Qza353r1T3p9ECJm6V6HQay7dm8LdnxFqFD9gukTcOByw+q90H+4PF4KrIQz/KpByasmbe/c5gaN6CR776Ls8kKJ+QzdU9ijuNNSCHUcCALnyls43ulzy5m15G2R
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
