---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: default
spec:
  encryptedData:
    cloudflare-token: AgCfDyLM8JVdqeOfJgE3PLcPn8XOYv9iQSTiKpBeS4SxBCPhJhUMly2WHus5eqFQEG/HgD1NlZIGIjscSMbXJ7AVyEXdX2ldCwhrUHwmFmV18aKbIMmnWweiNzm23f53FwlKFI1pHl+1a8R3bq9ycpBN38aONahPP0ZBWwygEmOPrCzm3EHyIDSSp9vmNpF/2MBDRP+tDJGWHwNxl8TEqcn6IVqyBHyXX0sBwZnD4j9L0M0KrNxcAnbhiCGSNA+1LcMROz8/GgUsDD3z/8NzU62z+BUDETxoQuLzlUTWclcDKs42QLHobIVEaZ82S58lgcNsMvXEs1ht6Auh70Z67gKHrg+GZ1yNnvpVevqx56wUiEIbI/nS247VSUA9lK7H2iIXGRVGePF1VAOUVJiyeqJ9jpqgscf8tUPiuRSFJDIRylXJOfLVBHcRVZON4cotSjFP5GKRV/WZG8Gzs/+UB4YGda3CUkUnoPrHQcee20pO2qRItWh8rx1ZqZaucW4d9Hnm7sCPCb5fRHVnIt3d/63cjNcyTs3Mw+UyXSZLZhNALDxcEKi9OVWD1pHl4NtgZrDMWl3+IWZCSpHULH+NOCGMnAO3I0Ixx6EkogaTmbEycPPHaf+8vVciJyp5FgmoZSxX+uy0vhRwjWlBe0fAAdZii9L5Hy0CRxX7C0bobwKYUl2VAFDKRwORO4IUjO7z1WxNxn2Zr86sJYQlmsl5/dp+7VWTNR6wMfRlSF1OSbO9bvJHXAEKYrtX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: default
    type: Opaque
