---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-rendering-token
  namespace: monitoring
spec:
  encryptedData:
    GF_RENDERING_AUTH_TOKEN: AgAt9Uc4MIwvOV38tKmpU8I+cWoJSuzLE313+CVlQwpTsQb0NDK4/3Loc8w5N4upHqI1VS6k4FX/KsOfyWTRkerhAnnXX65mJfzCX0t/IkizLbM6Xw+6dQyQppZYtovoNRIoqcQ1SlY+oFXNwkKx8WjguFBRp4yOjfcCKQilMKd0iFoDnIiOy/G+qYO4OGBxuT2BVEFAVmutMJY7DSRR2AgR9nR2nAf7DCm2cp6qQDUSlLqo3wlkZwjiS3OwEHrz7zHCuyykW/IFU/YBttHOiQItRSAN6wZIbK4xPISWHy89PXcEFlwAxr5kUjWeaQUR2yAnc5d9h+/1pTiIlVaDh2mhf52UcvUrhlcv8bHey9cNNonjIytI/LsbNgb3bQ+3RP6s7Lecngu9icKWy82LHPTdYppre71kyyNa5GpVsZ2VW2pl4PT3otrmL+aWIeNgpfIqAv3jizhqlSh8cc/mE8Io/TBdvekZ8FzObZ03BLRzynLSlhKGdPRvape9AdBPQjbiINnkkTLw4zCHmE4P4zGUPFqedGRkWLXjmePoZAD5zH+l3ZpncX1pD38wQnw/ucr/kWVDXrS4MWvWnftNu2igMJB6IgZ5iJ7op9DQj5T6fYUwEMCrFJR4jFYVTRGEM7jcxG4Ok9oVnNC7OgcZ/9TNBTcoRF9+6TbzjnHwaKcyLHpc9e1Dj8/3L9fyVvVLwh3q3grGhxmg6yp+efo4AFh05wgmk5JomrEwm8n0KEWlJL1LBd6PmxIivu6Su1O1dM6xU6TXxLVMPqWhm5quVr7+
  template:
    metadata:
      creationTimestamp: null
      name: grafana-rendering-token
      namespace: monitoring
    type: Opaque
