---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: values-secret
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCHAVoKHX2Ldq4T5e9AciJVZSYQNWTw9XdZTV+2EOJS7e/JsPSnw+UZX31IAyxYOwt4iWG62EKmJq6ghlfxmk2TJybF9j0kcoIF/9OxR4AqJXhQapP4xy+oSXqzGLiL+99DehOjKScTYLRw0OVGheQ05NiD2+KRUswu+CB+N+jwz14uZ8Uy4NS4tb33XEIbyePXtZyzdLnCNFGsxALwNidLUtwMyYCkpW3dESjZVThgt1uz0Z95nEWLRIDTtsupczk2TU0MvFeNbrDBHfh1Cr64McuQiVQPHVMnfGAaVaFkgKsI662gvoVQyZnQlu6HBK8YnDQNMsNYzLXIM8nfVbEWAKzDL1iA9fykjfR8sJJjVpoGKew8COfBpY9VVbVqLqWOfFhT+nN+wJz/wEIPgXb5mCqGt6Vn+7LwjdvCBVsjApPMzOs/bHfUagUsEVoyKIRSSyywp3zlbPDSOQhmo6d+6pkHQ4YgW6cKrHHm5mqvCQ6Jtjk9Q8GWzXdmwsGmbb/JzAutbnvw37Z1QisCdpWSR9ZbLwIhUxNXNuqkkJknw2vq2A2uDvRMFASnbyY658qvFbuukpHRJoe8r4eSJEIhdAAahJ3bGk1bWejSRiIaobotvziifU0lbpAEcPHjQWCQ+2DstTH6j/UHKXguGB2KxUncGPASSurxFsEcbQCgnE3K87atc8YMAwdSaE9WXWjZVkZyY10IxnJeFs1Gf8bg96JdGWDNjpM/nTiGQcf1o0Xx1OQQiAZKywqdQ1f08oPAz3nAN0AMQ57Eis5b7okwxytsQqq8vPKcEwvrCo6/JS8rQ7m0Gbl4DXJ9WWF72QNeZ+wwsG+LLsXiah4MGfE3HfYvOgtoeHaAuFw8IIvqt5iH+6sZtYxmfo1x/A9h0pMvtWN8jaRiJ+2LFJxV3DORqxgMGQ5p
  template:
    metadata:
      creationTimestamp: null
      name: values-secret
      namespace: monitoring
