---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCxF3kqRn+WH52Z/xfbMiBuOR2D6Ddlp3uY4FBPAjMH9jMxfQ4FZ244wmTi3P1d43Hd1x9pAbmdl6B/fA6sTGbPQxEA37nDqngOR9oDP0V+7dRSzp4kgVAUJze5W6uS5H3Q3XP5OlLmKmgzdR+hjIEU0PTDvN5uWpAhumneg3ZYUeVQ56kQOhlsGrBV7+k/q7jdmVrNfB6fdxryF+/PHOX9M2PYj3uwiIvS9pjehazojxsyfWjThyKQ2hh271hVoBcxg64jegiL+I7w7H4njxtlBggMXxG/4rFSva/Vq6APPZDeMDx0GMaVQ6HZl4Vu+eZe1c+W/bShxkXaJlvYDjR11bXNY0JB+PS6lIHc1YHWafd8KCKziq9Lo5E+gqNk7R0wfFaXeS2618YpYYuvqO5ZWXzcPha/8uLog6WIW4HcnY21ffeBSnzp+p9nrOEhaGEbW+bjB7jLvho9gcAStyTWQ8y+DzCQyzlJ2Ny0lRmv5MNn5ZA7s8h2WpgK6DsGnOW0wNZVUncuYhU+fnOAi0X9WvMu6XxrE2TWWRda+fwZYd+Zt1rc4+0tjgIpVnayxBA9T7xvdCDxOfWjILR+fToVxTrtrhopSiuTnWC9Xrw7AQDq4GjvQhwuXJ4jw4BlKMG8yoehZmz0NjJeMLe50UtVFiOI56t6pseT4B6JVMdCxVIkrwdiKvZlIpR4YbmzZkyP/pLXHK1yKO5/WVHwn63xy1NULuifT2pIvuq+iGku8zt5+xJkVDJL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
