---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgCyJSPA2QzERS9WTTKAKz4PSHGXuPhKNhhyB1HvU0r6+hrXYzKjNbXesZGb0yJHjS56TRrrMUsiX9t8gov8anNGichUaXe3ZKMVfQVM64zb4jKaFH6J/IbHqORUYquVpBx3lj8f7+dOzQuPhla3O2PXmzfiC3/81mj1RjzrRv5r1oPWZfDf5k35GsIAdZqXqy3gYIwjL2GofYyoABWX/1FkSu4MkI2xBnJMxKIkkemF69uMQpcCN+91D3DtKdmFIp+wdD2E3tJsGuA5t3h+5nR8DZNUBOUx8AUaCIUFhOd7cmm1X/bJB+LOyLzGGRraANlCeGVgKwVvkD2r3h1SdZPB8Se+UMRUCbFUCN5k9rQwJBSKH4ymWmWmfUkU6nNr0rMTrjixZT9hSSeXN5imUdvuIC1ipFEf20sSwbKi6LsOyP71Cfqyfpe4oCylDCQoVzSGAdweoA1lK/mrfwlyXh6qifsN2r1uJ6j250GmipHu5KTrL41xMYz4Xa9s1ImC3jyjGhYl/M8Uelt+KLh+CZ8xkQZyYc/D93q4385755N45UAwecHU8JioVGW61mzO5GS2lAYu9V7nBM7mhxj33YHuiaOZ+F6z1O5bNvNAV34fzoGVBTNDnukz2LI8y9H6V95uNjNzbyAVyULT4BWRzz4IIxNjP5EXSET2q63HLxkXfyPorVXw974o00G3fSkGquxJRe3GWlnWNtxcQgilwALK20g0
    CIFS_USERNAME: AgAQw4Sfqr5jzK9kr87ZBwdC3RHq9r6MJ94FVn+i6K84FsVtVNYNLdU2UDZP+UiTSnLgz9g/HzX269z9qHMBaqkXjPjx0ibhju0i5sqqbcaztaGTOXPVnICr0oSbsAvwVOKAFdlWAEIctJRNTdBp+h0ego6sC9Fom4aUF9oaaa6+cIfABnGDok+8PHtHSXHnnpP2guNoUbKs1XfdEtkK++rH9WzD0VRD8/XxEYTND24QhjludpQusPCKovRf+AZr7oFRIWYz7mkZTO8Er6LSPHLq/g7LbE6VlL6Io/bfhgBOjB6zWNzYaT4Gy+iV9TkfeLI/SkH29PCL8aTTumIQ3Hljc7HFdsxHIWRDTp2amtvmt64m5sIw/08ZFbV9jqhmoNppAI9esfYPruLqPeFVisv+4ZFjoqbJB52e0Yv0v670flQU3jeCecQFdvxd5QViQL5mRkoOQ+K64Wk3P5A6MG8AJnOyuCygjdLEIapLZOzDx2KN76uiYGMi/DohSWTiPM+83Btexv8ZQ3T4dtcEyTuE4OKSw32dFoZJi3B22nQiQ/GfDImVDPOmVNqwnofMVQ03Pj1AtAk7FPgF223/CN9iRyijj7OfANInaCeyF2oxiKTPTYm2BMRddBCjSgpUhW5s6UTcV4LxmyNF3X2wBVB8VKKyHSdScAdqDLDfJ1pNomlrAA+zhAeAaXx9HAH2gMRlrhi3Ow==
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
