---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCeQpvhfuUd2Xil26+ljYDGSkVbMYKlISq0m9zqJFk+csYfUM8xC5Zc7Pxg7CsdReKKXPTGAPreD3zuQ/6xZYiKH/U3Vr5xUfNaAwlphpuwIw4VTPfkvl7JWKYOGPXrHoy/7EBT5X7778oMZ6xflj7SKDsep+wzqfN3GVLgDcYi7ZJbosAlmYtSAiFA15PWhELLgEKFqgc5AUF+WKv3VBSW0dTDwOzhi748+7mjr+hK+2s6NQ63S9TgR5MxsZvXSjyR4HWBpRDX39GCJwHcVrwHEEQogtHo5KfP6RWVj9LL9QkscQ+1LoovIAA5IEzOTU7DpViORrm2BnyM9iyR09ekqdC+y3iuBqHmhhmCcDQbjlPTBpJqBYIo09o6+BQYI4YZY7xwLhUk6rs1Ii/ADTSUTanh0fXi0eTE59eelgb2ano4+iTS2TwRN/Mi69lt2SwP46gobXKqulzZLx8I6jr5UgLjV//BYjJAtyRKPgoqfPH+SqEp2PWqEQVvbeAn6FC10gSPar0jfP99T6u2Os9BdBOpvt/bs9A64aMJkdnVslaJ5W2S6Wg7CcnDkj9jKAjoPVyzLjhkWTTtrpxQ18jCRDg0ILvvqEefO8K5yqrVbbYQJLNh6JTbxQZISXECHTPQtL2rC5XKcFpbulyTwoP3yWHGEnxDRmq/Je0QGXHIURsmGZc5H5/STNxhHyhMZ47YR4N3JynTiCz/zEiktbVrYcK96uz1TPyXjjRSSgxbQ1kFvKfr9WD9
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
