---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgAqYwOscltWVC0oV83bSuhfqFh9wQmAPbT/dgvccrGhCLUvT2iM1DtgMC8lVsfINJZh8aHPd4JDwI37D7FN/gLFxLoVvosandJb/fYoqduucxJHCGmgfMHOtRwLqu31Kw6ScTHhGK7n6+MfKTjyYWUbkO3oUbf+Ccv5mF7Fz+9j/DVaD5jOA18iNwwG9cYTKeh3mnLKo1kdZqb1RQhf9x3BD454GBCYvdLO1CeJjNUvVPWJHQ+I086ZcLPH6T5oUuEYSd0WYbvU8Sb/0KEdUR9X7uId6jVoIDbs0l4jso7c+blcIxHGSRChSI2n/pIXhSF/j+qUkHdkfUnjE1AE9iFecBdrd+xnSj1dxRPfdjqj3+ALKCbpQiZnwe+97W/LhdX3fs+v2gjl4KLNr5lkFkANjU6MFCWTtMJpvftO2oIFhD1B/mO4dr2oW1YYaT0K0fmrQlLWjN9rxi+5Pw1F0wyHZmby+nJ/4zU+SgMZXShN0/CYn89dqMdk0MQXyPFTF/tl4CKPl8jqFGOwq72+nO84Td5bqd7vSzKVSes0fNOPpg8g+ARt2iVZX6hc48DdsHRMOrb4hhuztQn24Cf9D425yGuP5/99g71mYPoE752pivtlMCrybRpI1+EuCkmjEA35caeFvohlgd+JMbwN4b6+mSEL7FuTcAWh7rKvQcOtrsip8vSn0B4M7nPawBiPv57//K18n6okPqBy9GizlBOtG1oTCg==
    CIFS_USERNAME: AgBzX9wkxsQmhfe1Cr60eOJqb44GnjMbnzG992a4tg71T+PYZSFKq2BMBYCsMuXqRjHoy3Qs3j6Mc3c91P4H4hP5j1Fualv1xaL+jhcMXSQIlR5F+RtC8oE7SU5SVueO8DkcBO2LtcsgaUAVm2QC+jjnHLM/ptt13QNtHPqLBvtqbYHLjNhGdCmI5tvssRuY6ZGR7bj+65jNQUgibO6bSmd6QD8Lwjz5/aaGijmD/Hox9+FfacIiZHnoIjYiyeTE7RqkLxny0hOHRFXPn5yJK2AbFjbWtghNn/OHukj4GLUTxUJpWcrHtGYN1XzELW4rRc08xLbHgX/lJtFRHytNGSv602tvBxS1KJFig+SJ/rVVgUZd7kqNnec1Bg+JtmVRQIqcRdy5011+aHOlXWOHYqXaXbWDVPWjjnKXqpaHsd2DQE9crHrZibsUg2yCR+ApddKbLszdAw0mBI0ujOq2QlbvsLDFrlCedDPMvBqGBmSkq4/EKnHosMvnv2WUYynYlrkMtlOhuIyXtENO9G16SuR5zuXmufKMHptfot2L/S7yKgBAzHj6IqFp/TjdFiB/xYeqlpQNjMVCaStJbjOYB2j18EAqGBVi2BF5RGBkmA2Ii7MKo0qlYnVhpQudJNAfkbmBCxg07t40ogrOMyXsJALhdFRcc5yuvTgmgNo3JOP8An5YpZo1Sa3RxF9NKwunKFW5prTW1GY=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
