---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgByRM7HqzfflQqn1dmoCG1dQmvVkm4SNElqd5Hp+Wy2Jj4pyNl+R1/w4KyZhY8HSkyl1bxgsh5lXuCjE1o6TodynQA8rTUWlSaI4m58aGW6xOWwTVEn5JlO8OMHf9yAHG+nxBbscGqfycgeFoMTqgULpyhRP0lRvpHDLNK9tefKJvmJn9eGUqrsqe5wF3qFxgUBVitdJ9m1ZifsZDcESg+iTdNQRe1XIcDxFod15geNt9sgouCZtKlQU8xYmzujUzSTxiUECRS+diJefA7T5sHaAeFm2V2TuF/Mqe1E+U9FIFZmD0G7GOBBkYQZDQCOa7hHtTbdUEpPlgO7iRhDTFpxi5RC6W3iF25o+HbGatfBnJh0fcZ44VVyGhZtouJ8OkF5BtO+nSLevZd/l8TkIkA18hD9qri4D/4GZww7ac4M3JChI7X2jvpj+s6tBHC7msnIk499MspoabVIj9uL02hzoPiW6KVymlnTN6YwZhKfIK5EpU8dMUY3YJlfXXYts5M/746+A+p+hOyHJetfAXsMXHgbM2YNeoD43GIjUtfklPICdZKrQG0PQfHjuldoGiaJ3x7UEKGcE+s7Q8nQ55Vtfn9slTey4TH0aJwmqWS0R2FdWbBRMfxgeG4Hui75Q7/ZHBRD5HgRQGlenLYFlEI9TF539VLb5bA/U7gE8XR1ol0haXVQ18lflL7Gi2Y099DnfDsTwR8k9fV6kgyq4YA9by/Hvyw8KPoVmZs8BbifGOiPDrc4pPQD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
