---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgCtBtyzSzBH1XYbk+37xP6exIxS75+D0H/F/AwkUektuyG9SEBMeW577Mn/AKV6ouHHooIWmBUO1XrFOa/gA88Mi9SUxFY7LYRC0QcqgSKlrVteHnVbqHXjfp8KL/qSkEbOIbOp0zuKxW8H/LAfMevvKTI7Z/nkNVFRNI8uuxBi1VpGql60QEVpHKMO9GYiSUcbNVHcA+xdZOykJ+NoPItc2jmFYqDxH0rhSdOE+ZWrv/NkwwGeniTYjSr0Iw3ckAIzyb4zC+djbuMq+ZG+J6PiaMUasgrS9XxMvWoBc6fYEkFsEHrEBe/uBTUr7Hlz5zrL+QYFd43/oWTBfI3ikzFuVkQylx3gftn+qUssiODWyR5J4L6Mq+AZ2IZ18jptbrdvKn7xjycW4wijcUdcp8M1Iy6+Ex0LRx1VwYklz5SjxBEjpoThdr/K+gVNYEQGsSUhXaLhA6TNV7qHThZZuPcs3zsxqEr2a/lbEOrgHNJSE6h5owTYISvMqq/tTap3QUMHkwHxGKAALXxsHcfg8EUO0PeifEHt4XN3ASR6CF7etTcrKFGPCGk2n0iApYRgkTyWBzQzSEmoZgre2PoX/MqLaIgL4WFkZsIHojgWyB3vH8jXvAJ9pWFPCngUgtUZv/fQj/4A8w/F7SAX6hiCrvBdUKGHI3QOQqGQB9AgMTaUlJ3A7UMoavxVbqM5Zu4BGGXlyTdTmXU2P5B6KceFBtuEr7Jh7Q==
    CIFS_USERNAME: AgAejIslIhFeOtdMrVCTU+BKI/G4NgEEVBWmDQJg7uAi/bcOpzH9CNrXFi/fhW+xC0ju2OG02YrXCw7J8FLBPSe5S8V3NdoEXNSQqQYDzqGN32JzCD8xVlMZ4vchw6nBQoD8INZ1v/W3IHluojvF/gSxgQeU7ubqEE0faJaKhHsZQzjMYLYcdi1oyGtZ9oTVhWGZCdrj1c0ai8zedJ2DJ3n/l92o1Qr1uUaZlzQrZfDe2LLBaUR6ggVBwOs8msnoH1SbRvrtuVMiNVjbHRu7RKeq/oIPkkhiCcCcX1bR86b4eVmil5ZMqF50TyJ5DjppjpEwTkaF0WQ0PslN2QcW5p2d0I4WKhdYbS5x707u+X89IjYj5//fRBHNRUa+QkeItFy/uW6yA8AZEZjyIUx4ozVjncj4IKwTpiOjs+erMypAVdSCQgJajhCDSQgpSW3JtqVZug/sPmfVf3NM4tuYrUcD5czAi+U9ymQX9afsy5+PbLX8BoAYuK4x72Y3/CHgFsOidCQI4VAMVKMQv9YN+4JKLpFpX5rhghEdqsw286thK+k+BW17TvAB5tTs+mf4d5NL9BVQDBKkZMjw5lko92umQ3JZx76gKJmPJEDQMWNBRX92Kt3CceCK1q4+ogPLx2atLjCAMqE7SyVRyvtdED2Eu6FDB3HgyOWAHRnIn/yWx/0uqB9YpRhxfnd++bn/6YbQRoDs3F0=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
