---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAbcLHeqVMntT7sf1vuvc3keZgtBQIreb+A3z36DllWfOpOH6sq1m1yDcTuMmmM/YwINKO4BTQiqNVi3jczQXpyajnRm+9PaklcDktrV5YIQa+DltojpXpMjV14Fszr2WYIDBQJ6Aln/juWwtwHUKTVGUPXlSatGjuL/HHy5i5fZCObkmwIdaGGX6Za+uSo+sSgmh4ukRClTKH7IeTl80xjTkDbdNKDUG7fs1AAqxmO1Uf+LukRUKGjwI5ZY86ovuxJsdVeae92JraNl3a8m9bM2IqHyBK6j047D1A1z2VBLaxxlHZ3nDYhopxh+LkJl7EW7OdzQavLbjMPADs5J8BINmlhJgz4OlLvJ9drg78uqW7bETAy9huEYAkE/8SG38XQTC1KKZeYKfaO+1noW4jRpVtsEy0J3G5TZHlR1MeAU4lY+/YkwPnFrJJByyJXKUS/i4kSR7tNGszGqBcOTqzuNzsY7xKucFeosxzwUr5+IQVRFci3Eq5CFIkja63XgP1ABBHraixcNHMwUVbQusPuD8PA7qpkv4p2/tBrTuMlpuAca3kn4wkK98SfXDM9njJjpyeX1CcvkL/trr4bQpAeRdvgDQY/gpV38vHiBm7/7NXifacrx3zVQPtLF2cVN5u3nBryGrDitgetvX3dVJr7d81fEM0HYjATPiqhUGMbPzM3ubFDJBjA6Q5vvPtUTa5c2TaXVz8xy7Q5rqOKIB9IhfnVHCRfQlMHFFYKwlullRjlYo8Ksa4b
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
