---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-rendering-token
  namespace: monitoring
spec:
  encryptedData:
    GF_RENDERING_AUTH_TOKEN: AgB8r0rcEokPk8239X0QOymAFs7A+XRJ/Eji3iQvELwmdXFdPFXZxadhcTUArhIDbCXOU9F8V5QCiOSi89ilSF6tTFmiRo0nheaYePCcoxHvKKda2EJyD/dSRnxBjB18L8WqFzkY9kBKnYM9KmryPG7Hpfo3QIy0WmgTTl1ogQVE5rNd3e1F7L/uXja8vjAAn6IpJLb3oIKo5mmRSHA4MYEKFc6WbSaTj/BTraBN4H3VXqzNBC+TfEpRk33JCUopDV67etWQgiFJLR8tHbl4UZQh+tb5OSUKrvPI3hRWZwK9z6ynOkQdHv0PB8q6WF0he/56bZU1CnqXbvLE5FgRpy6CcNl4X0vlScCaHeBRVNBNt0JCw7obRa8knDlNPOeuCRqHINrN32w2Ak4GD/A1cZiOp/x2lA7RSuNMHuvKhIYdltMhipHQncToqPZyl5kh2X6yCZ9CDEegHBxmPgOoZ3cc0LCBMatn6l104ACaH592B0WAmRFdydbF6a2LlNl1piZ9aAHHm/LL4Ksn9X4BsklUlZbhrm99EmiNd8xzRuJ/M00j2SFqbALKKTJBgv7LsyiV74j3EYGpa4ReZg2PFU9g+5+Dm/R32KJuv3vff44HS/cnqT9yhfz2qDO3dzGGNuD21ldKd3wlyXvZjQDgMI27JHs8eOFYokH0IZxTn5Lf2NOneh5nR0qx3MUl751tdyZoBmAhrpVYNr2bF5DnQ+SbB2fXbWKCFEo3Pps2JUd2m3r3t7HbimpNUYOy0pGBrUwDnoH+6R1VE7dAdusaJ/Do
  template:
    metadata:
      creationTimestamp: null
      name: grafana-rendering-token
      namespace: monitoring
    type: Opaque
