---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgAoBiqrvSxlKB+KtjMQCU+Z9kLm5WUTjJKMNQQcs5IQ0OT4uaaZmz4QpOYLinMXQq0hZj7RodL8BhTQIAoYhAXtmNQJvC77l+KRO0e0vTKnr1M/+6KfylT/4U1HBq3sSAh7Q0AxZ9ESPemqeX1MX8NImYCBSgtXaWvFPIWRjEEf/cJaZy7iqj2wSsRYLW4vFh7lK8FnimdA7lRKFs90k4Iy4NxBnhYIsV875W0Np7SWT5f6/9JTeqSkqaZeR0QDvXy7HntSDAeWN1w+JNXUf8c2UCuV8/ersZVWeFBb7YIYqcX0ykSelnbFrtcjorKJizpr+zwENU0xRUM0fNUYDRaHaRLDRtdA8bEj7wQWbo8Pbk78miSD/qEDrFsH/mmsaQTNSYJNqNYkPja/a0+E1P8ysPExtvBzdtnBM2wqWPGEms4PViyKAtWRoLIQuzJemRhlx0ElncKrN3zWu0SpaRM8Iql5OUQ3duAauskcQrh06nH6TKWo7WCIMQaagd+/l/tBJ3LrfQku08Vn1fv9aSX9TqfNzoxld/VorWyMIHlHgL+ZF4vE6oYsbyoXvQ0gUrT+uVz5z+1OEz9KNBRvM/KJvLnRVJ8QYtOKly1KivkQ+OhR3VSksk4uDWGvG6SW+G664Gf5VWESIPM9IRlzzX+tMLYHlaECZOgtwzyE3fxTHDEJOHg5J3HNSfZ2bPZkG4Ac2EJhg4ma6IYCATS09Vp5hb+vmA==
    CIFS_USERNAME: AgA7NLcf0MF3GFQhnTF+0TIm++C94QYM+5EcRULlclCByUaOIWdHe33DHeppgBY1exJFZ3kufC4TyUNG3Sd+JQUzvFRfCexX2n29SwGXKBH0SXvnivu5EcCRDg1gRItAoDUgrULl8uY0KdUZIBaabtbxaSCQczwHSD+vPwzQDXNLCxsNbNnsY1V3+7ECsu7Rwo39V4ye3ybVJ64frsIU/UtQ9YQSSMIzR96pQxCpogJOjCZb2bI4oT2lonYSt5aG6w13pbSpFn2C3pUMIrMJYTZVstpxxE7Idba1GxskGoTRe+tbZPBAhjOOqvITPIgKbcpWAJgtZoNrP6nxQPK4EZA6Q7w7tFoGZ3XD764WNDGmKR7gsM7+xXX0OglxsUGy3qiGBOZLmUcgor5tOLB0aLqpH8VP3GaeX9ohbKRCPB9IETi9o1JSUVzkkT4RSDQBjL8KDQCQr7pfbQugL4uZByZA7nW2jcedf5AmNbIPC0bKHg0BWLrjz655rnC/9lghReJeGkHdQD8KCyLSZGaOrB8jL4hzEIM6/9GeKESHHRIvIhQ+Me/zBwjJ+gQXa0OPqto+GNDRa01IKglSciOWDZo95t5IYjB6nLhuLIPITwIFsfA2SmdXThvUSkuMI4m0eYEeW2M2cJhq/P36jdtd2yVXQjeXr4rMpDRBXz4YBtOLQ1ATcivd4nMMKfaCKfi/mSrv8KtKK0c=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
