---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgB7JilWHEhIy3kUSb6XqDIpY0flAlUxG2EkGtzTkUX8SJ/zwEyVA9IOczokg27hTGxB0H51U/TuX3PMGB6Dve9+GlrF7aDLBTxsqWIe0VAuNl3mTTQrc9m4gAncrlVPkwMkwB7rCVwMlHaWp9h8DKeRA3mYyd0RbWT/FU9eTqYHviOkJoRwEuVGki667sljIWXd3WDIv6b6qEVjNwGqpyEX7kCnRQPfupOGUE0qjR+mMxSFTO2MBaoqeRc/eLbFO0mFCvNc68ciItuVonQgFIfNz1yUV2vMl48unGcAuuIONC9RJzNPGJc0f+xoZaueRZrxqjyjbfwPqFAx8P/S78MWPOwJllmEFg4MlvkYU79BNtLQCDCqDk1qkj2d0IofYz/fjKGck8aKJ661ILU/nYPlNtmxBpDJ8WqJsVGa9WIX6U7IZJ7LDGyu07KAdO/cKJE7C+LHz8CF+KmCqfRLW5EBDiztt2jl5fSTipQAPp4ZsTKMZ6XKRCoyi0GIEyc8lMjakFa9ykiDT7eBxGZLeYQdlbp+CnDeK7eG56HnIwhLffO4iWLgD4XiO/CkhU+ZRN3KjKuyCNjj+Ht2SfqJeP3F8ljGtNDn4Il+D0WqIT7w9cjBgmNjjQ85P+SIApwhD/Aznxey2BJ6A5W10FHOJR3kZBtQLobAFG4q1xR4tInhFTFW6r6ENAwV4D713VdSJGGvC69y3o/CJ/NZc1mZSzUCNtJwb7F3sEBEcjd9RT75ecUAmNxjk5YP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
