---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgC2KNxuLh5JJNKR8/62fRMtP89B9QbYZqJBhFoqZnKsifIxn4tt7UzsWLn6dT6Y0FLk5MF6haBloVv+I8jYWnP9JHREYOwFm4DKvekQa9krxQzBR8KsmW48oclZIJgqLoo2L0lxuTqcqFIh4WrS9KLLeLwks3eK8qAj9IDFlLy6eCuwRj7LskAlX3tUkOoKuSBD+ACJkTEMVpo+zIXg/1fD1LRcQJJXNvvjsklPpvUv26cW7j3ZnpXcVYYZLMdbiWZ9rNWF4DATevcDmyv8gIYlw6QRY4sdGA9FFsc13pQ+c7N8SNwNIxR+cSrmXOdzjba1FUmZR0yc32jmWtN+YQX+USCmEvafIzf9UvBAzOvYkEUyyxkEgWCoBEE/vdQzVgFiXb+kyffcj8tPMgGa6s0xAAx8I4vhyj7zBc3H4vepFAn0URNgGx6fTB4XUYYQgvt1ScO0RiNQIVoqtSI/sUh5QGong+TGzt0e+RjyWJcSJufmIEkOQW6U2jA77cf1Gau0pTVJW81w511xELC5rjrHPTfBi8Q9G1rvcDY43zpywBsw4Fn5bRPJT6Ykpd2sUbzHLkKSJ6q0HQ90liuo5Edlj6nCJWrfGQ/2+5hmFuEQKQ3AtH3KSnyXomNqII+sjzaJijiYq8RBAHYnqfOarMYNu14XGWk+yo2FM/+hXQd4ouGSDKSc2w5Fcb3FpqRqooGYsOzfGD97qdLgVSnnoMtfj8HwVCApscXXNQPiRDZC3uf/IxsPyLvB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
