---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-rendering-token
  namespace: monitoring
spec:
  encryptedData:
    GF_RENDERING_AUTH_TOKEN: AgCUn6oAujwTBIM8k0uaa1O1j7FHgW2XICUPzwE4eX0YRPNS/e6KIe0MVNwOjAf3TOjZmakMpnt1uVtKNfSvx4k4z2pKcK10F7E9Z8aAXKKtRvNoiaPBK7uRbKL9h9HsVGGFMK7gnvuxW/pQTwZbTL4Kq5tx/yJ+LMlhSRI2bSFN2n0mazWu/wFooRMaNftBsEPtysyE1f+j4sJ1nOUdaP6y3CPr9LUUmrbhB7iEagXEsIDivGjALxgpZOlzgm9WHboAs4HXn2G9XQtoCgKW0BKGMJ/GJf4jr2KHNBofCCen/e/2HFuo4bHZbA5cqZIZE8zEQNl4MY46cPplWBL2m8TRjStBAVveN7JBODFIf8NRFX3LMf0IZI1GegoR6BA8DeFoEiRJ4ZQQL4Dsg6tjTaxMD2SO+ZbAHhZTAfo6/ZTIvtJ0aA7iJSnd8cUfd30LScFvXC9NDFrfsskbjuk7mrOYpP3CQ3cQ7dwD8nYzcJxu1w8IQT5herg8H3Bbstz4HTnmHNGlmKGsBxrzhjTLLYvBtpIWlgMDrBrSErKa6yLXFlmH0btg8rzINE+SLxMO1PKwvZnHn/6X4G/B1WZGZL0HCSibYfdfFFQIg0c07gJEi7Xv0OSBJolGiqM2aXoOGJTucClKchqigV5VFNRNl3wWO4SAsok70g4gWEw20g04XqbOSTwqgeQH+Rn5F6Od0L4nleRMlLXxGM/oP4pTJ/7kIRY9/d3/0EKX42BYVnuOm2MuyTkBYh5OfVbdW892xXJRi/nrT9CCqnGiMxETaqXI
  template:
    metadata:
      creationTimestamp: null
      name: grafana-rendering-token
      namespace: monitoring
    type: Opaque
