---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgAP9HpxDCplhTalgY0ExBmIRrkEgRjoJgDXtGsI6/I5+26FTGMyAKBTED/aG226Hxjo/Tm5QgZrYq8FpWdwC7O8bHptsoSwFQpqP1PdXGP3hl0BtpzTDUwgyhLr37Abbh/Mb2Q/MLziExMgqBhM36m1U5zgC3AEzPdakgzbuXlcya96iE2CFa7uvVQKLxD4KSCvrPk6avjRf2nZZB2r7eisFFEMv1i1yenKMHqEKnHjlHfy2/AEaB1g33jSuDoni1oKr/WzXFoBW/klSEHK6OBhlvuvOHy3WN432clB4mEhQlc3Rap2OpkZLzDgvSxz3qjXKKkfoEfFBvH5BIJ4zw4SleU9LpVjlUmgNJ+sz88FN9B97EbmniyUrWs+MgPNgpedvMr/ZHjepzwsvI0dW/5nGLA612bAPP2JraXcsjSYFK2ZsOD/YNVsRW5b73ZNcC/O18ABghvWkDgpXrIboMhmn5oZ7uAJcQdbYeSbl//yGA2Pf+o9yrR3xkaF9KIdhov94XYe0/G1Zq3Ka8JN3EUlWfOdzvj8xuh2qfyBJ4ZHCIacuV4l4XzpxhawhtKgR4PEsfSXXXrpCrnT9zObYwtuNheMWPk4BbOZwbd2Q3gIJ190FhCdMiIyFMVFtsrIAean03nlK94SMzSlv3Isplyzd7OQCr8YBiqsngW726XW37KpM5RgaPnYMdRCiWYS1C3wkYQm+93A9Wn1Xk1/gl61V/B+qA==
    CIFS_USERNAME: AgB3abnZ5aC6Tgp7G91Sg2EqGfC2pfRhdqY0lZfacHWRQ09xrYAS7uvsZ/Q0ddQJfih764i9aoi11EcVKkWy4Fox/LzX2Pb5p3B8v0yZ51J4xah+JKwktJWvLxp2k04IzVwnGNEXRec/kffi2oi6eRPmUK6bYCtKpJo/DzEO8sr9suVhOQqFA8YYOOjNNPbgGWa4z6yfKCnvnOgK+jhDzEl+RCrrgJdtQ6bgOy7INXJ+77foEhLxeGpMY2nen530kE8mNVWaZKoP0OqRwC9gX7h0pQAMzJ6w8B8YX4PNCt0GwDUoXajS+ditYNjjHPXWiB53Bq7DLjbWJlgjajfQyLBQmzu4W1VgzPB+lCjGTtRoZbHDmE+I8Ywx/+AQSSJWRy1Iz2Kxyf6S6mAPNrtcMb+g04GcQOLBf2Z9W027/GFriqJzirv+Eoby9zqEWpWMxsre7lt9Bruf4C0OwNdW678blkTXeZPoEGpek4xbLHHf3eNuCPfLoPGUKwdbqpb2zAIr2nFIlPO5Oxmq3XTDV2HeO5dtToRrj93e5aPVeuL0+PUnImj0j/tECgkoTG4DL1FRwLwlGiyvSty8SwQNsp/MjtFWrjfQ6ztbO0qJdQC8mrcgX603Iai8Zik1FcuFtxFrKB0SMUwAoaQaXv5/S7gGQ74xm3xogbtYrq29IMCFsUr29V1VXUngjsJVtFgdbnM0UdrfWSA=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
