---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgCGYib/LoPstw30xLR7vlosbtFyRKANklI8Ogyosl0pHJD6Ic49o6DgEQ/FT+94pQiWOGIxx4Ezgi49yDRMu6is5sIBZY/wkEDcB9H7TPLsoZ6XHp0WcsMyJCEqCrReZQXpgTn4SPkZqDZ5ztOfj5Xpuh9vJm1NCluxMmbG6PQS0mUUlrCshZ1lBCzENFjJipNBHyyyBh3Tervla0T8QJTQQuJAe2i0Yn6rv47+TLhmt83zRBPuaELvRWid6dfDnmKxNY2fi9zvF5loW7V5EjAULhzVO8vZkE6U+x1OWTJzQGDI8dDXAO61zIFsXmwGra9cQYcuN01uP3Z1gcmcsj2K9OXn9Gdq4PC5rWqSVEiT1wcICI5sIQ0OjYH7SRl31kKDiDjpKQo+RHyM/SVTdcclpH/BWf0AJLq//gFglp8SEXYHxkkRAQUTZAtXFWnZWt125B+piweTsI8TricoZHDs/zEulQofUez7aoq6XSWGiUivqGNF/R5kBDg56GJrOG4dlVdRzPTotDyjJfojb819PhTL2jFHsCxuuHkKrPnJlPeOyqrwsk7E7BGRh0FPkVRf4NUiPIJ0G1wELwm7QajG7CU1+mUI0HfyPtf1EkJ3UIB6MnreJuJ8oBuw+FPBBjapIDZoLhqlTtgAXUEkkgNpP9PMeBlYOBU6lIzIU3joBgezpJUi3kbm9aTvx7GAtxBfvGX+IAyHmxvFEFyADnuC9paw
    CIFS_USERNAME: AgClJteT3xECKjbdwFNgyDAhfxMTpZC0+gDYktYJbhJ5LJ0WOC12vb+EaPVVaoJwVHmYV09Qb4lNHfMgQtRCIRBg9vDuAjwO/WMJ/QPQKR9YozaXYh92flQaz4tAjXxK2yUP06fFfrEQ8bHNMFj+z/zo4xkpOQzbD2FRbB8p05H5xAxI8Lu8WjV/7RrRrjbrVJkpldhCanPqGea2eT9JLKcg82TiG7xZmciSnhd8m/BcUXY4Si5MgncOJtXQKm2OBgycsbdlND5pMPSFfX5JE6QyvHe2g6WKlz7t2T700uADB9QYE2G1/Fi+0cuazVqMR3Lqx3dVZUa6WLYabj0qnuoM04sAWkxAxZESeOw65bAR4WaWt0tKHF3ZBikEb0+W2TzcmZUlDDTcqqdfffppj4KnYXBPX6+nHEHroizp3VwVmpBvX/Qw5v1kYMSKQCD4jOno0asIFsftGgpHieuiKQunhnZCfwaFA3CpDl9KrCF5ToNYtQUnzpJW926hw4pey8VAEJuo6FIr/uKnlxewq8t4f4/QpQKe49Cbj6aei7lruzez3zlgP9cfEbByC+x7zj15zQwNruDXEUMy2VYd0ia9x5Slh8Cdq27vJSU01JoAKSzFSNlZn3sKyW1RKhCrdJORZw05ZwzgQ2S82r7kzbnClvP5lTN8s5R/jRvRxHP+6d9KHAA1adlHY4UjJOrwojVPqNDoQA==
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
