---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAgs3c4XMxRoyYNSZD1HxZCXuhtPdRgT0d8pM2umkQp6Z3Ulrjedig2sHUCzaUY8zqVNA5HPJ0t1g1fzpd8BCzl+nuVXPZKBa9v+s78TjaYfCz/+tnuvzqYC9x8+ZEsdhpaLOT3sCPM2kdkyKBXpjklon9VzquvlqAKn0K8kPG8CER7OPHZRzBNTm0djcMFdHGbVHzYCZR8fXohqxYVhn0+7CYfnCjNhaQFARhhgCHqJrR5md5tYMPcsoYAmAaGAADlzEcbJUScONuHFyzl/sdAc+j8CM1u9qrKC2RTAoF2H0jDx3xiAcgBsCeDo3yNTy2CIKiCF4Tmaa9ew6Lc97gyyyop5IAI7YpgvHLkH6DPMiJ2Pqdexq5DXdamXDG9GR86q6a/Rdl9UzH+r6eN76uyASVm4dyuNVOmkKpSgdh3Dk1+cTAuUtYfFFKYu6pX/F8MfLMeKU18Tu/d0CeeWuhhGxtYR88e1eD8UBchdxyk62rRoJfAWLmns9TGzT32VIS8jCKNg87mqklpx7sfG/jwD+dRNZvdKgiTKz/G7RUzsnP+9k6B02h8ohlAyzRRHlNBd5PGCF6JydQI2l4PqmPRN1ySPYAHDDxXeQu9MeZZE/neHRB8Tk207kjxihZQDAYEnbe8ke23QQ+Arf/AoFqOPq2u2mwl8lFerpAhIa8M3/gCYj494AKOZNNC4/GsIQWjeCZ9U+BbVkENjxZdpjAmsa9V85bLWlAR7i+GNAMP5921luNZHPDx
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
