---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgC5vdoQL+sR8ARzaQ//84fGoGev6U7TyijbsrcL7mBeh7hA9QzCNLCC/WaYx36WF3vC1P5Z7HF53CFlyDbR//KLA6Ef5JJa1lUnLBg6S6WHx2XmyXwi4LiDOf+U+K+HEq4DzTXxb85GZaHaKkAsYIz5ZfIe7rgir9w8p6h4UdwODlQgnzEGa6GusHncwxcEhmcqPXGBCLUdQszU9uNDe67WJzENcyQwngSQPBrnWLtfy8wf61mneAZb83A3M0T00Wem8j/qn4dfWFrBokwc6mj2BxXYWlbfTjhlCKfAzfAw1esoqr6EAdFnBVytEjqdb/CWr02poWZD64AxvNmT56fNAPZnwFDD3hfnb7YiZ0lQo7nmpbF6F4df/R3tQiM1+1kiqUc+Gii5NRKKG/2CLYagQkIo8c63To6bE+RwZS8C1nLOYXTcKeq6wJrq6Cm5OhFohhYRe09OGpl6H5enmP9mHR8Pe3qALyZGPqesdZkc4NhC39WlzHyr4bc8ard/0kwI5/xqfyRJF9T28hwhyYx83wOiV+mFhWX2KHfxz4dztFFOrX2KspTMGXPtgohovppgj5tbQPKGWSzt3r9DGO/jurY5ctVV7y7UaRsWLl9NtMlHcvFkU1PwGmdVKk7nLEpPuKEkIJ+MKpJF7U/OatQEYrI2DfapW6Fb7J6Tu9TOrM1nSWReM+kArrpF21Ilv++ryW9iluzVKieUANUyagIPtXSNrVqibCJP94aCKMvQapJu6MRzpkTr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
