---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: values-secret
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCn08CQCyo9A7VKe5JrVp3osanOxsHIuFMeeNrfpjMKqIaccszd/R4ug2lGVOW0qI6ZRel+DLC/aS5keI+NhyYPxbtkdHMrS2oHBjeU1Lz4bLl3c2QXyN/RQfUBCOzUErOD2n7favAYLLIUCzPXDRc4v+OW2ko9mrs1kVOK57YckH2Qmo1HQkMZNre0r1UFqLxbObBjVwjKl8KcIbfAHnOoUJtVbEDi/XUauEgBQipnaoWRgatC+zSnK2PxCYpw2tp6+tMUHguvD2ICxqMw3niRdHEZJ9zxpykbnZoQJnNqODmXoeXC5atviUrnOu1AwrBZQozmfjj/1hN7PFsUwusg5XhXGHhuBrhkw9WVKkdGY/ik1nO74eXCAAqDAnGyeUQogY2kO/DIroZ91045RwYkgXrr1vbHMVVWVTGpEaJLi8ID0+Bw+SaPR31XWgDupOHPOCL51UPuVK4h/iM2jkUDuAbw5xhZ4/naUb6JJEV4IuADdlgOpTMwjZud3uyJ2V1NmFkBbDcsNi45hZi3dcAdrEfn7XmzxhAIBNj+RMeqp8hixXtCN4KrTXor34Z6aUN4MGtARFZOK13NW+1Ay0O5X4cfmvYKuHdWfTRov/j+aX+QnILZZjzPdeax1L6GDr36wFQKcmDQbEOlxz6vTP/vupK8gu93Y136r68m352MJKomrF3Y+SJztsBaJ+gnPpuIx987qYUWkSZbK9G1vbFVMt9hp0wJ/RKiPEqoLe2giRjw027z3SwTbmf1Xj2U8GBa4s+l+sM5NhMy6lTAUqMRYSPV+TYBZaOdqS6HJwcBvh0KhKzGEntTVLa44FfVsPRZ56XfZ378xRdKJZk81sB+F6I3q1eYy6NDYNLzYAetUiesD3N09lYItXPytXAokhwF3im6emu5dAieUJN9wRe3pwQWoLGM
  template:
    metadata:
      creationTimestamp: null
      name: values-secret
      namespace: monitoring
