---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBYhQVFHj4OorqdzmVeW8mMx34AABjbJ03drYCVakyTciyGz4ai+77VQgW4cZ8X1y5x9haErTSryXIzRyOYEa1686PnAtNpfmOka6jM5fR5chrqtQJL0DT37X8ZPH1SgH08Frl0UMb+fk3NFw5spzhochTeb7wWULQI39GWTn2RsfSAyxBXhgRhkxXAgcp+9KddNeq0VTx6xhUceT+nF08JfF5nWutyYBpCm8gq8B+CuUMrk/3g+wD/dfyCCEkTNCYo61Getco1DsHeARbkMXYbHvURbvvmjNxUQU7mgmWaWOF3/sWlx6cJi0Xwfc3LJkW2U7zBMUekfpd/05+CfJs+718X7DR0SWpQ1MLfNZ8U9AdJ/2QLofHwvkTNdwzbZZGCQZyCgEzCjsOm6QKq7jJflyOWkYgc0rnpk8J0EwHAbqQf7ySa4VIFkpLj/Nu612JzqlQUCMIgWmXkoGLHtyp6I90NZ7qO4pPyIP6uY/ujgIl1hEG/ruQv5wCs77W3NwZBDvSuK/AmM8XWHjc+5BEXyw5WmXptJnFt5X0IJG+hXDO6fhYQnW1kWUPBVbjzHCh6bmioDKifyUNl+UfP7pYqSHKK7ZCm4bwYw8tq3i6nZjoHUx5sgWn4WN4UAoT2PZ8uaKoIR/rtpBonda55NYxRFUwOvj2unsCoCEKZ0n+ZRHQQIS2dxjGb9mJ33XFk3i0HK6A0UOOzR/WBmAW8vKjBmN+J2n99fn0hypmEgnFkmzXDLl28ajnr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
