---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-rendering-token
  namespace: monitoring
spec:
  encryptedData:
    GF_RENDERING_AUTH_TOKEN: AgC097cvz2BvTq0Vk/yV1vYu9P5Ylj49QuKIV7bNsAhLcBhgF/ny4Xi70BoAiEOUUU9HfdpkdWQ5fH+L+h+uQl5MBB0NpSmQnpHkIqx/zVr7qiprCP36MHEVXj1T4oErZh3Dr0dLuP8yxERBnyBF9h8beQ3yiTXV0pzKg8avU3/g9NcwLIsgny7vq7cpu+4hPLLhm00vtL+7qS8e2Y2OcXbp9eBPeCDbfVKNznYKSv61EUMlqyCCYj7tCysW3t3McNMBFN5EoY7V4C27iiA6v9puuGaeDw37r1R8fvIOvaPD6H4pVCYQcIi7ZlVdeZmMJvFQllm616NH0UpQBjTxzCLCna9JqMR5AxOEN0fLiGoU/61+PjXnoW8PlAxrsWPdBjfZVE/nviNjzYKg3LNynHmr1cNJWWlUOo4nXqQ4mXiMzmQEZzJHxsCLCFR+IvLlOtsIjWubAQdHqdZTIDjdPwMF9OBoVtbc+LsZfd6nQULvIl1s33DUQY5ETSt5NNMDqsoYFTfMsGqkYDIT9t+GLydHz/iZ2VLFPHE0m8smi1Bbk+1Lf6gmVFILZAkp1eIdq7OkV4ESjZ+UQRYkovIqhz8Ad31GHZCe535Dyj1e3asQfkEqHOtqxoBTgWgrewnwSv7aXdmRMqSZQ+gdBjqV80ldEXl9C1HniRnfDeyNXT3KxIn3uQmNH60BrSxDA9fEtWOQYWxuLsIWjOIYyj+5ughFCsf3KrFXhOTydgwAyp/VpxSaA+ZyVzxGxvZPoEOy/fujk7o2g4S/udV69tNkh6sh
  template:
    metadata:
      creationTimestamp: null
      name: grafana-rendering-token
      namespace: monitoring
    type: Opaque
