---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBtEmXSC1WfUQ+ROr0vEAd/QnLTEqmMogddMmOuHZlZhBu99uiE6MrwjmWcWFnZwSgpQ4NyuUnzQOE2hWBu+V2RSkw6fx6chHOX8ogHVhcNVuLnwyP+Q2t+pJ/O5dswUYHPJ+XSOrDIhC+1WW58ACgBxgIqDsprCvX87MzxggLQy5aFUrs1HG9af5vl/ku71pGhkyTGZW4ibFvz9x4XUmjT1JideixD7LQkK3sK87zk9s7YHXMIwcqLV0e5o+/P5R8OAlK2Hh5QS0bFe4CH1O+izkN2vLnWqJlP6ic5rYLJ6OJh6GZfpfxoPpuQOMb1mtU7xyr2gK1puPzbX01K8KQuHQ+uZPkvKC022tq5+azF3IMBWKNH+hOWNy/BkK0lngvU2zbaEIyyfMIgrBCpiRgHSCY+lutfZKPYoyb6keP3GTvT18gIovZHvONkj3FB+9vO8UiBIh8zI6HbMRPDyfgTCXDoaA/T0dIszrP0F57arwNZ1g4sjd+vD09zt2sXLpIM8kkLbzW+nlYMVkCYdiD/g0az9Q5vGtC/aNrTALWU+f+rpe5v7T4jx3oouiip0ynegzfIogy3XZUIpbbsusH2UPzJpSgggsFkdnYFJpJnTcu7kJVQ2ri/JcqpmQ9eEOoSZ77CO4cE2LRrRj6EvlQq9LdTJ2XKnIeXNmpo22gzlaGi9AaV2QbQAv5JIWIN/EXkZxG0glL3Rsy60BKDwQyzpLSJaw8DfOVdvbqqq3Y2YnVnsK4T7wbw
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
