---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgAQrJvUZfSoKNmBM09V/54D1v9PCn7lQs4EVdpwF8Wz2ju3/e34QTau+tKHiIh/ptleS/AUkbwZYyod4tsB7IHWDZTqgJgCfySLaGK4dTlvIGB9AmBlzrJqpPqzqnIO8IqARN0jtLXEz4oErktMp/1U+r5bY5Ak4BwkQtWoaGgzxY5fAA/YfbJPsIbwUPebnO8PIeLHLrgQjl4l3n14aOEScIHyfQuQAG563OaVyAjmln9DqssRKgsFF7zqqtf51JqeV5SEhWEZFM5xFb2ZOofwaY2k9EU9WtoKXQmWSU5qeEIH2/PMjS22SfxJT+mciDU8QLiRUMdWILSnd5C/bVRxAkJsQvmuJIOmpuKSLMLH8KWFNSfjfcixGgW3K1QtNYJ0d0uqi8jNJIwC1Ye/GlSIyWJ8IlZdQg7QX0GobPXbR961ltSH/zZIPe9uhsx0uXaT+7CCIuYSLr4RHZVbIt1lYZQ6NC0DW8DyUDnAs9eFLQ9lmlpOIEe8FQ2gX1KiVMO94FPW9qyf88vKcbY1j4co7kUclUvDHknRERaiawYORt/Duzh1/lvw6/Q6CRbd7GeYuiUoOOeWNjuDTxOxICGyyOhmtbNdWQ/mXZlOjuqSOUY/SlkitE30dbHH1A//d+4LhUsuUT0b5G9znzgAh0k9mASMGXWtQqxPHHVuS7kdTigYIzFflzQBb6zlOs9aPWIrfdlOi7UBY9jcWW+YgdlrX4MD
    CIFS_USERNAME: AgBuGUvJUDQ971T0xrrtosuZyIg3GUgtU3VtWTJRZHhxOf99mSiUAsKyl0xnZFVSjiR4u7pI4Wvugp1Q4bduvq4oA32NitQeuHhXTi7+uSwkHraxX5dGS526kjKH5WL+QLq4xr1fQ1/xNjme+v4TlyUAzdI/hwdijxuS1QGIS9cTChm1JWRCs4KouCdcKLLkXAOBFYz0olJyQgJwbTG0LvUhz9Nk/0ot3R5wOiyYWMaK3Lh7jkzBOf15oBPmG7yvwMxRnLZF/gDRhCSpaG8T6G0cAaVZRNAG1KSj+quFUQoHAWDiFYj8uzwhhgRfyHzv/AZj6ue7RJ8Rqj6TG6hCdgy5FJa6uNxCtK2El4viIwDYOn6f5Mm1bRKpAtcyo3Tj8/GpHCyuXj923qd81bJyuGZkAFu/90qfi/s9qqfBkxTbu+UcKVkUh+TR5g0PCD22VcUtE2ttLaW3ggrxNtP89sXEA1Zaqv7weBgK1ZEgKDyqhiEbs5CET2Qs6bdODVSyeHkAdnRwCHC+SMSgL9sYYC99TtYJuvWKUGUR3S3IfJnF4Rb2NslkcVrHFm6DcaJ4Fif5wf4eJEiCW1legEcEj9Cn2qffBt/NOBzwXhnuAcjH7ZLJab6UjgbYgr6hANkeCFa8pLouIqU+NNeADNy7dDC5n98AbddKSiF2h5otLRC8uU/fAlfB36LwY+SrNmj1qSuhxa75+A==
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
