---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBmV3ZmRmOQvyfmSI7oD0tnGF3wAjGrB6bTHfEhoBa4VPgRu6jL5vUy9vPUDvIEmvQWbTus24IjjCpVoGaOcGDxY7cEBNZb1jzMNWAqaN7/oN2mch1TRFUXtL0LIprEK9eqQ+1uZfKK0JIdyDpwRViYk78FvC1u6bUYdBnEJ7ovFZYq34xkYf+3kvKWJyW/pEjptdaZ7mRlT4hbQke+IjlWSyoj31mWlamcafzef6fO71uGl6fnxtftfad9bk9MJG0/akviY/0lZZMsTCe5zm0JUKkqAAjqQ/31wfE/93D+gN9w9POSoRSHuW1SlcVrwLmjoX2Y8Pl4aYOUvkdaoZtOFkKo7INUFMYVzWzcAxNRxoAvE6N8jlBUJL6/s7fekVqvDgTFtjkMycck1xLy9Rko4chtazjgKOvW5OW93XmsEmZllRBvSoA2xSU8NMN0bM6IApl+WIKOEH/54imqklP9N0x9afOxY0uwSciHJEZvm6ueUNhCEjzpy6CgXLk/Ip02vc+SSPrd5wQPaPwxnFu9k351qvD2j5E60G9tA3nxxxwuYhcugYd7gBp3EckwEtVYCMJjqBMvBo1+7EMNg+HlgjuFUrwYcK+GGy3L7eH4imK0W9m34bjcZaK/LmKfvKaBQVAzA9UwkR2TDxqC5FKZFRZsAxLW7PoFX7I+re2KshZnOodxRaer/9nwVx+ZP98Wb0tGhq3jrem0P0FlyVFqgReFqrchUsi/mlVtLBnDCv71u2g6fJrR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
