---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgC1pn0dABWusZZPKRxM9A5K4fLz/wIAB/f6KGs9zfYxzj2zcYq6CGCqN26IpDEsO29dg0a2sweRi6kQt0A/DT1j88LxEX8Bk8nMojO+PTxltdEPwU3JjRooY7u3/o+6pb/61LRt9EWG75PTNJAOzN4w5y4/7jFxtac75cY/EB3Xkh8LWWe3pkz0sV4W44M5nPRpL1E9yTq0iHFwdQ51u2cXjWUeigCtN6gv79cGt3Z9mZ6slqmiaKUZjDlmrEPQn3RAB9qhPrdi2N+ycofC0WBvX7a1NlMEHxZT1ZMM57vc0OIL0QbL5gOSuwcNYmDv08ebDH6stlGagoI949jgOSFRv1H4lEVBBpc/mQ0RsW2oYg4FyzuvOqmM9hDP6JMLA/U7f/yuH86sQladuKgls/1TnkJqpg41AxuXJ1eVUh9OlwtI4or5MJe03OW54hEXJZHapjwyD50+AmOXg0cA5T4EimWU9nT4rUnob16FcNW+VIFCJ86r6Q0AxKWkSyDL7SDU0H1J6jzoi4f1I1883JT8GfTtxmcjsWoLv5Lb4rdz1N3MtQMRgCvzKzGPwzjDJNPQtZw1BWXgvw5yHnGdDR0+/GTE/zA8B/3LGCMA+0wjfY0uGjFMo46PEp6+GRMxi37XKcqfuIcDrBF+8aqEtV8Q+KoxDTYyVY5s5czMaSCynFWxsL9CTvbYY/Uve9SBDMv9qrbdeHh3yhC99X0xTs8EV2UTZA==
    CIFS_USERNAME: AgBkSsnGYRGY3WXNEVoQ+teVXIUl2vdV1/XCr+8E0yM7xYbryfNW8RmqqWQBtPdJKi1t8rMbKvWYHN7VxLcPgqFDbt5n7wbbnpyGlF/XN4ugeTkSDOzoyckOtN9aH0UmP8h5tmPfXmQCQACTAgdtaaFmnnFELY8D284TS4AE0ScaLy3WKoeZbSySG9vubRjcvSTJFBTk2570ODfpboW9nyVBPpYe3TRc/c+fF7ruo8iakwXaZ1MqfUXrTt6pf95wjWkane0vxDZXvThZ2koD/mGEhMxEyGQPeGoxPfRqnFYxkjLXgAamfFvG2YJK824tFGkk9UkViXaEMpI3C52RCuI+jGuNEeW6J7lbiMBXAGlpDsWAxJF48oKUY/nc7wpGei42GzkMh4NDYsuTnClkyvXAmkwtTx5bAIapjiPiZ8w3SQQqA/uWT3GU6VOShvX93WOC9abYDE3qzDY5QBYayO481MJCunOgUSx6SjwjwXc2qN3GlKTwFaztwIfZsOoY91xPwDuhhnPm7pXF4WNWO/DB4/O/lVeUrXTG5y/oSGcgNNfljOssxhoKOKWYwNwzz5p9AlH3yQyUOPpBaOqVTJXlJUQIk9WC2aNL6Mtd9pjpkbaxHMNAf8kDD8sJ70db4NGteOkVse6khz5oIiCy2mmYp9adAgj4ov3rFqRwuIW8bmf9K+bkb/D3bmlBmBWJFgvehmgAvdE=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
