---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgCF+iOh1qqm1ZXxwDJIv1jlq2K0ttDFjgY6Dbe5vrSC+UbDNGhnurMPlTS6hlqpzJQVP8Co4fnji3H/l2/AEJL+P0by6EraqodcKBf+wdFB51OPlp93/hj2ezHoDM7pYpTmCxCVv1kb53GHPOhgUFi9G6mZLTjo+VngZ+7/qGW9Zhf9vKeVRjv8JEu+2UBxYuhPT/JZ9VbsTxhO8EHXYoQLO0O6R1VBsX6u/wEq8wc1xTiBwmpPJgbUv3lelby8behsJrQP3nJwHGfW+p3T3kml/hq4VowqR0dfbC1MVsn8e8FuKI6toikMgnS2bA22tAp76SdcVa4Nk8PVViFt4GMqjbnEeMto1EMG1+ytApvxWCtyu+FWkNsoIyYyIXUo3uxBcAZfRbHO794dvITaS5uJnHX1NTv0RdInWV4liBfg88m8LnHiGOm8jenCIMz+tdftcwx71mrSP2N+XPVyutCquXIkBKSgcRCVShTCGK1CT9ZKSDHNNbjYLYjlaSgHIdDcnip5p+9qxM/Yw8rKcjt9dovYb2GKmjoicUTqLpleoKqJzIkX1dhHYpcBmNbo73Vmys4IR2ESPqgMWl08PWPjJHFNA1wWeOaG2+oVD2NqQ6TOu9TZqyw9mTPPtj+uyVOlUJp6RdVgwfNIXh7+ngbqlcW+/w45D9t2gvGeRgLUBLv0sPL5KJC0+tCMUveiVhxsNMlR+B8a1lWNCwyyTJxxcIr/9g==
    CIFS_USERNAME: AgC5+J3uFKEoRm+YMcRpQP7HxSZJWOh9wxOwUeKR8yJnxS1NJvxl9fELCXO5es31+/mcaTm9+3ePlimgX2pN2YGvL6jqybPTBQOapqVs0HYdQeclEZUww6kpDbUX4XmVV4EmGIkft+ZqRyr+Nmrz6yiAPNkn98TUxduoiYI+Lx4qF9KxhWof9QYLvu8Q/DZesQe4ytq5P4XHGfxYNB3HMI8d+33Z5H5geTsybseviQTisHrlcRDvCqepWSgILaz+EOA7M7QG+PLfDKDGc1jCVdLja4C+0KBwN/vhZrAJ9OE7DFoQHYj10QxGocx6SJPqFJVqmKutyqB6eqfJwihV8sTiBbw3K+FUeIry9DFZZXbIxJtThEWdVsWHm7UqOFNQYxRZmG0qLft+1/CJT8WKcfRcpuRfer8HBG8lrSq5foOJUoyWctmJ6KbeimLd/zJU6O5QDzyXuvHzLVuTYJZ1/yiFqvyx5Z2I2eC+aEbwhMQuzN123SQ4i4pAPHu+mxQnudylAo76KpQDNeSJ8dclJEILgBbUREyotpzqQRUDOta1LJ/wbecoNgXEOvfvjDRAPKz84wFwrDv/hay1oLda90WlcbdCRDtecHqYhFFHvefPraW2Ijp+OoAWwNXumsqzgvHAFCS8C/m1sGRUypR9nFynNFojoQF9Urtl1m1RdMolrUbas2+TUtcJ1UsmVh6iCv06/TiqBaQ=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
