---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: values-secret
  namespace: traefik
spec:
  encryptedData:
    values.yaml: AgCTIzlQega4VpGHG/9RacCvFczIVFOwv7ecmYFzslP7sKyJlmRu9Q9WN8LAxZFd2aeVOXH998zy3CJWYwF8I7D7k60m9b/U5YVJps8/LEd8AvFEZd9PZzouSOH9NiQDDtkp+LBBdFG0tgqbimYELU77qFxU6FDyCeyyEcBoz5eR5JeDPzpxm+vjC4lrMKkGoY9jlGR41Twi6vang6GZW7JdjyO0H/Q0XCjzzL/rUf81DvWvZpMlgl7HzhAFolWSrxGviC6ysIZIVrbcZc0vKXuThhoQi0FEJsZX5v6+MMh01zqCY5iYK5boqpMVcM95BlJPCx/z4nEg/D98gYjiitEYkU9akR3YFtev8q1xxneq1yVxaLPUYb3+znZxxUvwyHgxWM9HO96ZufGPztCPQJpmq0RjHirsryQDbz11YPuX3jAeo18qMfa10A8YRG0LaVYXeimuvXGYJiXRA3D5jghn/7DEd84l9dc3NgrADViNg0B+eE6QGIFvPY4KF4wynLyYBMIjeCqOSF3AwbqbhcT8JOH7QgZfPSbNbaIvKfnzF//IK5HoLn0a3ED4y/eX55aXBylGfLrQMSAYna+rpRc+7ZszjKMxyNq4Ty2Aw6BttLV28FOiGTPqFbmNL4huc7kvhb4/ZEIxkiT5iafiReJN9oHQdAfgtoBCzB5ZdUNrZ+fwMZMaUo/tUciLI7CLemF36RYBwG3qp4dNTnNxbVqltJuPACr5FbuRqSdx92D8LnViE71iEa6FErMhvrsGDpq8ZBvYtSFzI4PGQmsSIznS43mDRI+12ng5XZ2HHjA9AzMFyjVezsOJArD+hvWu
  template:
    metadata:
      creationTimestamp: null
      name: values-secret
      namespace: traefik
