---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBNin175XwnayZ+SjToJWGkwhdOjp5mVsRVwFXS4gjL68G6UQAN4F3sOL34zkC2Fa7CrnYFa9S6T79El7tgv7gKjZpNfXPRK3h+OxZExVtFSDREOttVyvfJ3JTAe5OnpFf/H1C3f+Ky9JGUMq9npJZRzh2I65+i8QFipOh5K5DGF8ElmQUYc6yxddpt0YkyFKcXEMoZ9t4s82EuhKdT1lOJxh10FC0gXhDmgcWJBlCzXqDp15boogct+WGgqU1uDxOuFi76TclL8SVO0IFSOwUsMwtN3TvG+MZ1sxkjt2JNM6O/xkoOjTeowW01O+6R+8E9QsOZ5xYA510F0S9ggWpVDtnts1PCFoF15NJqQJoMtWug3I76z+VWJiKl3q/0uiv+7DiWNdjjfQeOR9LaFS4JuNOX4xuWTTsOAw5bdgou6Q/PH8raTGks90Jrs1oufNi1oslMILY7s3KT9VS6kKymNS6szJsScNyR2VViApOpIXqVAFNuwolfgV/MEMv/LkBS5F8JIyvmolghms3qefRkrowseZhexOAmpna8/gxAzhXYC3Xt+j3Tl0W5cPDPzmOMP0PyzGIgd1L1dSIlp7fby1gmJ2a82++Ct/2V65+x/3rBuCWAz1KR6R7P/YtBoFqqwX4RAPOWA/6UjUkie3vvc8Lume/95oVl2oDZh1PBJeHQJ3ce6KRIeQ8f4eazMToQXMCrxEKO52rwXT4o0c9DUbGzlcjTd4S/pvOI5KtR+CvSZYf2O4yS
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
