---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgA2Q2/740yTu0m2dax+haDpkToU04GD7G7oLTgeV+I4St46bjc1Ih3qanyYobLqHdlPLev1G/Z85j16HxMjziMMmAobMKPytl1s0P+Qh/O/pl3yjv6eoKfjfOuvXP1YtILn/W5ad86UF3HJo+5bmFl5X2TpNOo0K5Lhi8aXyEwZc4d2T9ep3G7sg1CHZfLTgVRqsfrJdewBSiV9FZWUkLia1yQ4CRg6OQZF21wnfc2ZmtBrOBBYyyrjBpEHEbeHzaglVt2VpKxqjf3aiOoJFcFczvlUKSNg4vP4SdoKrRX5i9L8/MWgIhfr/Rr0BPvMbPrHpaqmhDsLabyTbTpwtdohTNYsST39bTymQKTWmEQdv1MnuJ6VYadlpYF4a/Wf1aRxYCkZVA/Pax5J00djKCo0q7NExoHmhJoxWLYtbRObqJ6m6FkIiZx5Fe2BI7jk8Gy1BluO++tShbvCqb72UArkxPpW6SS3NCVpB0P8/S21dEhzT/NNZgR93BzvBaqHpupzFgh36MmP7QSn2S42PDuqWCHk6euRPRsxgQBUAgXrYq8ku/l9U2XpM4c5p6GnNNDxqpwqq7Uemu/18AkLb10k/3UXI1rfichBGnQ/N4gFGbWCR57Q/qQuQKhg52HvgRUnjTgUFh9GznHIL8J0vLBf71EX0iuc/3TNGAABr/oRqIBn1kWY+dm5n0cLo3ehrENcqCDZPL6OspFU/KapaG/C3U9JVw==
    CIFS_USERNAME: AgBQQgbaQ+vpNJYzlxGddPDeugvz3HGE4rtKOAJgCq1ueJKqsyVTs61botme20pfJzrYhCpMUL5WrlMYJZKJsHJCuJb3absONelNmFcWsiybpU1v31NCb5yzFhBAnk5tzot9UvES3Vl2vhkIBuOjEXMZ0+pJ7py1ZKzdjgt1IZr8WEoa5uic8Fv61ZCERiCs1aTcy/IAz13Mi3SgxQ7EUHXOztNwbqSa2ofTkjuc1XXuJL2By9i+3V9b6L016yZPppfI11jY/nV5feU+bjauiBDQhYJBx2VnWHCJdI1lHaFvvsHZj7anKU0p3nmO3HUXHABkwvV4WRnOf0eIEAuUYfhT97/BQmi0K1mOMOFsfQ7/70eacYJiqYQUS04OXFjTydwyQ/fPjXGnQ+NjrtZ00ANzCipaAgnnUIQJKKTja2sSE6q5IvE1IiLJHoxKnZ7bA6yL/ZQR4AIFRQwmlY57oKZNWwB17ZBfdtwAhWNM+43vUf8K3qIUnl4G36AQs/u2eD6J4evFIJbWDvBgUtV6zXAn4ykABlE7AnxMynEEhkqJ/beambBv4UemIpKMekEb0202KsOm0hhIaAFPwV16dnLyTNTNizqHqzm0iH4Xn/ec0o80QYdCXyLFF+FBqeIN1u73ik61/pmnNNvlR+o+jmT68+tpGn5g45yCuz979z4/gImVt54TmlH/f4QordWuTfeO1MNAKA8=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
