---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBv6yuzuLgvgkT5n9yHBI9qFBbKAfhaVoCHoO5HSa333xbXXublOlt+eu//efUmakurZOK5qu3Bcke3/G4Bofji/LnLy8XBLj8n4kG2xfTqFLdV31hySI5x65aFv+MgNBDubmu9msVnVfS5MR9p0UKiOjDVA6mtlW5S5hyK3hRoaSbWi02eBNFxrDbFlgt6ifm4rVl/cLpG6SlVHiO+78IK6qg9jTae90ghD89pWMV020DQMHRaZ1L+yCEsugsGGnQCORhEeOcwBnBJQGqcp4YmXTONfcpO+34kohmQ6rgXNyCkUIBLNOx/ZLNTuER1v8V2GcXulF/ixUnOb0odzp4n66kmU1c+Av75R/Rla4nBayAtXZRV3atVkTfbqLwTNjkOBVjg2J6HA1I94oL8H7cBJdCWrgpfexB8yN+PkiwsDMm0kggEeCeIAeDE0cwu2Ak3IhTK+1zUgCHRUjq0/895h2x/9lYhq6xmFGX1cwlVTNqj5QFW/YB9CVA2pByJqXlDg7auSGADpoRiitxCNY7+DeapbBhQRspJ8gYoq31JLOBLxFx03Z7Hha8taNJGIdcrtK3eLZNLU9Vo5ROM+feYDxv8wrzRgIJfDCsu6oddoL39Wdwy61IWdybJi6PHUXmRIgXISnhItPhjOiNlkpZ+rCYP4pQyXeSV62I/MnYz6O24ovgCnkl5DE0q7sVv9bC2JJ/69NC4ecTnRu4hA9WEASB/aumxnyzT6VrMMaatIeiHJylFCrpW
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
