---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helper-values-secret
  namespace: traefik
spec:
  encryptedData:
    values.yaml: AgCGv+gMrdzyWXetipMYKhfF5gb/JuQ0ZTKt4/U1NSnIRgBQvtSYa4RutERQeLphspWMNR3qkTKZovdnh9fi7i4pF5QCdJuZF8Eov+xkPmu3E28DftegbClCWEn/9DJapegGvSUkFe6YjEdMCRVx0hRXGBNLXAEQMTdYvC4qzujtaCCTlZCbWKCCMiqSwt/GheTs56PZ2RcBcVLlyea8wgbHYYRGfrlcMTQzqRSg+xN2i5wRXDYpXxFOZg9cQVTeGO9fjJDCIf/fZqcB/c3xGRmj6/wEiFN3hJIja7oJSydrhu+Wcc7M5XgDUvactFOxaKYZByGTt+Hkcv5Ag6wxaTOb7+S/V6cjBcGtiPziIji2oPz4LHFh1lHwkHM6zJG0bC5JURrmUK4OsPRGxF3Ek2aOVC7/0gTDIDSo5+nO/mj5EDyysyuGSHEMvty9xRrlXRg3fmXyy4mS3s1eVbKgPG168pzFtd2y8QdTjCn2yMVvLFBGgin5ym3uZM3ra269gFA9Q1a2xKttP7+MFvWIuhw5VsxE4dFYWeHfldQ/Big5r1WTYc/OocqevyBwJBpoUYgwOT0mvwpVzMuovFdzV7Dnr2fz5eSz2ZbsW9iX0m3DiV5pOHaVcBjkHDSF9vCMO28weB38zQZnV9CTwCGEwkyM1jOB7GsRJGwT/HvUdbHABlBgZRnqJM545R9wEsk8tEoHJNYQmB9cwOoWwdxS4huffNjuHy6IiZ2mgffxgGeGU4UsQn9hgiQ2FDWusyv+8Eu7mvinODaQ15dTkTIBPFDajJ20vTLh7Q==
  template:
    metadata:
      creationTimestamp: null
      name: helper-values-secret
      namespace: traefik
