---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restapi-auth
  namespace: cockroachdb
spec:
  encryptedData:
    users: AgCCS3EWnoed1Op38P5Em9YO0BHaOm10E7IoNsT+Yj74u4jSAIVQAUz2RP88/vi9G/98zQuiEW7snPfjYXfspYZ5VhYK0vrAfcdqVfdwJ7JO9bSB9me60vQegxQMVEToT/M2zlK7Lx+WnfjTcVECZz4a/8PNWcuwX5LqiMwHomAIwhSgYgcPbwy0r8JlcJzLPQR43vdVf7q2Bk3OtvQWSmoKFSVRG8/J/fBMAr+yQDeMoHkT1wq4CcDHx6PUReWDMHO8oezgZTm65XQaMcEIbKJzFexwNFCJDD/mE+y6ef45ulUOdWC8t0z2oFUEuId36oGaTR651qnsajR7VMjtIjzYbn7CwIO61aF4GUTtUuWRdj1lW8bTr6HuEP722IriqAMU8YIj/B7kBVqZg5V0wd/mOh8gTMaBpIgKy7NxPLAD7kZI+lRmwTWUr4l8f7Erozkk4JJisSXCO5RvHDcueY4421FJAzGMpxxTymS4LhIuUNDVphMJmauKmAvqAfh97oSg7qdCDB1jRr+6FU+qxUCBqQHqTZtWCFZwyxIuJLcouT6/dg/75HNHY/MlTYnQwnKFv0ZHtY8L/kzTEZoq/PkVt7aGpfui2CqCU2tl2/WkNRm9RMUHThoXz+08tWGNZ8YzN1a2x/OvXkGsi9FT7J7Hax4XgMh4IXieedvX5ESKYaPcE/ZBmVKaZXGS9wBpvB6Sp0UljK55OfX48ex4/h20FJCVut/0kcBKWqmi7Aa8G7RpCwGGzCeG4icRlA==
  template:
    metadata:
      creationTimestamp: null
      name: restapi-auth
      namespace: cockroachdb
    type: Opaque
