---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgBzlp5OmDsBFQqftmT/e+f2zuYJdkgKsu7o0pojNlCXDMx9bHLMdaWtm+YtudTe6+K9erk5KmDu7CxnJEisFZr5qla7FmIxIrtLAGu3KltXATfE5rOVUHNFBvM8/Tav0zJdczDzFVF7BwmggSDb2lPTGGXErC1mn84iz+SxCW5wDXOO0gGRKIhaX3JtDyNmx0qdwDk6fA6Ue8VWvXqW7YVsuoS2xsFG1Dumby8SGuBqmMXTglp3kmCQLo+S5IwpZJSW9BiDE1trK1EACveIXWvn2qplvHOSBZgL8VCTGFNiKyhZSnfxfJg0C6vf9KsM2eq/kS8ZcZrUHM3PjbtGb4JSyWm8kEdia8MQhoXa5iKLIr9iZeEFjSSL1j/rjKU6Y78/RbCjLxBb2rtsrnXtQFY8kBtP3OF8OK7D1BpovB4xJ5lvh/R3rdiucEGkHBoxB9Sq2y/IC+R/Atl7LUHH1N/91FhIu/mRUHjhMaxO5TEspr/R+0UQ4ee7FYp1Tof7183Z4cSUpKveVrs+i51l7MQb/hoicWtDKaof4UVuQDPRSe8YCvT7ARSS7Hg5srAWcviVsbYB/WrgRU61Eu6LT5xUTKiMMUXUJ2RB64exBpGu6E5+v8EZTIMEvKNmNZ2xKH+F8Jl5D/3ldMEz5XLe+Pey2rtI/dZUvC9Bs66G9Jsm85twG94dysquxlTigWpgvG9fiaMFhG7Jv4UZaobDuMx3pzyIJA==
    CIFS_USERNAME: AgCEEBshKV+Qzin1TAxc9a8zRbplHN/QvHg3mOdoDX2njGiAVoTGGrMpGbzNw2KyhTnmoNxvoZtvpbdJajsUPs8UMTMfdGVWkcgKrZP8oCGc3MFSwAy8BhH//kX8uuppoSJWxRyEkcKoY8FFNAzXWsxf6bOhhzm3YEpowtXQAB9kxeOzAZBhAEg14M+L9DwKRygCrjinZRMzzL1CSOSEcUjEFa4bAOJRNQSxKjVTBQbrNB0TN3HMvjH8qS/VMbvGnwd2/A9z4u74gO0T4DgMB6ZCBvlsWpzFVaYzjdmxYy6Qbp7M0Elc+pqfDUHwmHeimWFKdk0r1RUVdMJAtBMeywSmAWbeqn//5S/9uYzKNRdxmdc1puyqXnq/kH93Se4j72X34vvNYzrtyo63WNHvNP6v0gRhbdmql6TOiV4OC2w9P4wrUf3ySNrGN/E7H5ltZlR9ExAJYd1DlfjtDhsotu90+SfJERvPbkr5eu+BKacpHlY0Vyg8u4Z39HKDhhVhMLEJOWq2ALybGpmGJ81JrscTTGonusb0HZOj8rMyGe+gexLBjeRl/wncqXV6o9q8frfKV/BzlqFyW0n+q18edXneX+K6kaOkyn179wOZPC6yw3SLagNez8P8QvpS04xZ7hsP0RugpCBe9uhJeveGuui/wHl2vCqCfUuuhCnm01VmAL0jDDwGv+BQm6xSBj8WSrDgkE+CfEM=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
