---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAcx40POMQ/XoA700F5FXWu0LM0zkF3Ndr48cUtshj0knB5j1s/DWUjWwj8XegxmCj6bo5ZVq/1jxGyd+qToXAlI+mjeUx4pESTXabboNLOe6UY5iBLtteNRvu0Oj1ZWaVoeKYwLoiECjsOmK5E5vAK5lD2JJEBKAzdHo7Wu8igPV0LosZL1jVkNOF+UiS9aKCASxAT/Bt6CkXwYJ+X4ERlGYiokve3LPCaknG5uSeJUlu5rEl1tdk4RsXRYgSDwmZ/oE/sLaICTwEkaQEUK6OKmuFFfVgSTCWEWVWu5sMo2KzTr3BY+w/x7m84jfYVDDwufvKTCCeFDVh7DvC2kpZJN83y97OVnIFM31scvEmOuUNDKbZs3V2SDDdVhQd/ZqF174QV4yxp2/rZtuRLHJSWnrlHwXDfMhgxBhgt1RWZ9d4/xtaGwLQ5MR9eR6eSUUvAe5EPndz/QU/tuTFjEZ/YKV7qZFnwh5UPTUtAD/nv+7T87W91EMQ0hc96MrGIAqtkZ6V8EdtdTXa2VQxzVatb+WDSCcNSpBOMR83e6earfQWgGHXdo7fpQFMnrdtSXXt6l6mxtkDPv4bpxCRw1Caadh6knpHsXp0H3/5qsO/OzpuCs9putrz7rYqrUZ77G2Gj0TNA47+bZufsCGXzbqk835jXByfb3bSl+uaeKOpwVZv8fu4a6uIcbyUqPCwLKJgRiT9eLR/BlNscAVpWPk34EasXEjSfQNhs2yJPcNOWtuAaJurfncaj
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
