apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring-grafana-ingressroute
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.{{ .Values.cloudflare_zone }}`)
      kind: Rule
      services:
        - name: monitoring-stack-grafana
          port: 80
  tls:
    secretName: {{ .Values.cloudflare_zone_hyphen }}-tls
