apiVersion: v1
kind: Secret
metadata:
  name: activepieces-secrets
  namespace: activepieces
type: Opaque
stringData:
  postgres-password: "postgres"  # Replace with a secure password
  encryption-key: "change-this-to-random-32-chars"  # Generate with: openssl rand -hex 16
  jwt-secret: "change-this-to-random-jwt-secret"  # Generate with: openssl rand -base64 32
