apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: rewrite-headers
    namespace: traefik
spec:
    plugin:
        traefik-plugin-rewrite-headers:
            rewrites:
                - header: Location
                  regex: ^(.*?)\/(.*)
                  replacement: $1/traefik/$2

