init:
  provisioning:
    enabled: true
    # https://www.cockroachlabs.com/docs/stable/cluster-settings.html
    clusterSettings:
      cluster.organization: "FooCorp - Local Testing"
      enterprise.license: "xxxxx"
