---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: values-secret
  namespace: traefik
spec:
  encryptedData:
    values.yaml: AgBhGAQE4WeAKzWbw0st/mV3XiNCutKeHOKNun9YfAg/swYCJGp7Se5Uin3sLaK/HefPAunwNncUAPS6+EYrC58aOh/ayr6ha+ojvU0gHSf41USzE61F2XBUYcJdrYQj7tsM+51eXnNaVwQXsYI/ZDinnBVuqriACqiwy39Ug+5DuS0oiP9BrIgCytxSHMQM5+IiuFlVyWOgiPoJ/hZv9/yKzDUDZ9HDr9MH3d5nK0dM7/O7SynCU7Dwzz4lcEMqtQaNBE2n3+Hj06sqNpDB320hmptlQSHaxofUomeRpppDzZVDUtxFUJT8RRmk7Yh757qJ0fCqeWfyuuqWBXXV7dy/t8L4Vn8RD7ELxz6k15CH7+cS7oIB5/QD4hD7K461+VuZGv34g86J2yYibMnaJ9vZg6WnaX8VsW+b8T0ZHOARbNGJu+7UdpvCVE/TTJDbn9Uap4OxH6uQVT7o65sB/g97mgbrgS4wV+MqndKNoGZM0BNaDfx/jgBxtid55sgNAjUYpQYOjLzhM8jJi/qSAXQhmMqB0ADC3U9v25XpTosCnYvjlolWT3gI3sYye++QnyjGOl9eMPj/voWDxZnVoBClCnxtevPfdf9AhZzyJvsxtwmCtFpuXjrX4+QgZ+0ziHD+qjMjDtB/r6zK5Zf3qJHW6gq7SCvJhebpHMOdean2bfCHIMz81T5cjN3f+s+8BmdnQn/tEZRCse5x2cth3QmU8WvQDOAiLLHLOBCCFPGeq/oDm6cDBs0xrdbWybDZmLQuGfAU6H4bS8ETGFlW9RSd3H029vnIGUP9NnqbwnVCntSxRYnglGFsS4VEW8ZJ
  template:
    metadata:
      creationTimestamp: null
      name: values-secret
      namespace: traefik
