---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helper-values-secret
  namespace: traefik
spec:
  encryptedData:
    values.yaml: AgBqqPpHhoixhecdDpdRVPrl3eby/7rAFEFNQbh8Ln+x7vrnZJCtJU9sQqlxenKQRDufJV0ZivSveL0fJ7k1CdT3zV7gUKwFHxV/ZzfUK9iU+E7fD4KwRyJecfqsb0fDR5Qx6IRkAYZUSFhRfcU2FhXJo/9Tw7+NFwuQ2aToeX+cCxj0LArR7bAcA7FuhB3iwiAm49uEZ/H0WbO9G0mu3Ez3OY10BGDIIlr8sETXobwp1/rC4jwalj433P/fhQ1oVHiEgVJ8kj663YfvWz7Lsm9WpI6w0VIgBTlDqEZgXkPMmbv1R2fIpm11++gKyS9pzNadkg7OoW5S8s+KLsQ3y8Yv1hPLRTLieZ8nftUXuz4fbU9BdZDXjYAjNQNkUP9SiqC0D/A8Rumff5FMCcto+JcNFGzgJhrriZ0keC6GsvxoClYOlpfc1RtTT8JayYjUwk+SmYt580ift9d2zphnCaIDxKyirVV2cv8ExrPVLyDUMDfB9DXns62uUMGp2XE3/IjNJS7pVWwvtrg0/vQ7rr73iVVGEU+Av78zAXo5Qf1C6yMZv53OF0DqUZ07DRk5/Kfchg43HAouJ+gB4W8uu/cLy9AJiilH2r6chaZpR0an3b/52CHNvQXZ5FwHeGohzZWsmJ7JCMsAJkUPinfB1iWITCTyP4WVCGROVVKA4nwvD8Tx3sAu9J+mATS7nCu1DfBBw12+AYcytR+D3V0cTr9Ug5tOMoVGZ/PVelFSV/LmukFY+sZIUVyMRkbYCAnfFGc6qj354JTK1sMwEGMIrlGMSXIH9FNiwQ==
  template:
    metadata:
      creationTimestamp: null
      name: helper-values-secret
      namespace: traefik
