---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helper-values-secret
  namespace: traefik
spec:
  encryptedData:
    values.yaml: AgASpbVOgBAzRghCP2oq+wHipi0sU31uwKVmh1DRX7SSf9Vuh44L+XnvXfFWlT3Wx75IKgb5C4VtFjG0owRQhF3Q9fh+PYxx6rMvHnG9L8StTmCAhG2DakPoZahAZe4ENdIuSSfGDjFDeFemZEpxT0fJDNCyhLlFOTZIrxOy7ymHUb0Ey7HKKhZEBYY69vIkbTdW41Q6qja4Ne5+tnTCBxMFABUKiUfoam3T93lMSzQKq7zZUCZUMXAhBvv9T6GXYDiRprsLmpjYkHY6f9fNy+rfD+SsSMlz1Fsm9Txa0PQPYfgH6WMBYhEknFJ4vVmycKr4aLv1lZkNW7TxWgsQTkE9MSohUuFKHoroYSbekjv1N94kATQoZ4zjtLZ0ZAeGQbxyd0BfXMnGgsdjrppGHlT9MRHXMi2k+SMegpzQ7oYIf7uX8OoZDVfcag12TRVUPgmMT3h/k/e/zKFIfOmhCFYT35l4kYzD/G4DB3uxmgE2pBRuioWT+L5HTfBVriXSDxFZUFu11QoRRP7PXxWaJvP0S5DVzKbhzlNNM0zJTZrWpJI+V6OGUfjKOs4bNWEtLEFdMgsPopMBnstPOaXJBbUMh84WV1VZS85WzjsXK4robuoXwPWab70gBvmileAqnEWlpKw5XT5JefMWW5Ub07GQhhIXh8xkDHVzCfLR7CdbfYWzMfc/Ah2vcAYmsljRimO8Brv/sDutuTCE+hkv/yEYwUDp7uY6FWyLmNWqDbXhTiiZjJiRmjZwsuT067LADUI00WiPnlwS4xPI2uAwS2gFsrX6DIuBNg==
  template:
    metadata:
      creationTimestamp: null
      name: helper-values-secret
      namespace: traefik
