---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: values-secret
  namespace: traefik
spec:
  encryptedData:
    values.yaml: AgA71IJLj/cY8aGI/e0D6prs2FNSvQbsjTxAaqWhEDHE30DgX34K0uZUCPgLID7LJ4Fid6Vqyj+S51Xl5/yhDk2RYq7CB1g5ufwnQEUeV3XYfPHB76V0xQ+KD3eAgmEPFe6Sb/0uV+i7/sBGCUF2E/ZpqFwP91TwhMasTGHBVM0t/efSEiRncrBbfFat/7+78lKRHeLUc+if8//ty93m6RAxwHwoyaewL31QtQvKFlXpnJedvHRHgJiURzl4GpzaeA1XwLKc/Ptuli2fVB0wCYqQV26jlb2o3eH8pZ+SsHv99262NqRzh+7dpoQ7UXAUVurVMQXJMW8PDkjJzZi9r0CuMc30wb8I2MGyFl7JV/dEJYVwC6sf9azgWRxFBON8kmP4dsSpA5yyURjVo/fx+a5QKTRE6JAVLfNzXNWqzpefAudctpSLrhPfTKTyo/7SKolfyGvTyjKrDfFoLOjy9ADc1B+CYDk+Khlw8THWVxkYOu/QAH7/nd4VMXyepydvOfhvKIKHaAzLBEYfilTJ3GPFWSA1os/8IZT/o9SdaBBAo+H01HsNyHyEhEZ/qxgtq0qgldGRsJeaf1bpCu6J+yd/ZXTy0zcNYSp+H0JNkmsJPoDrWz7aECydWDuRJ1hjBEcbwV+iN+EltO5Mzc1wlhUjPgGdBq9RL9Wv6g19WLPtnQhC1QB2RER3Dz8rYEgjX1PD4wDoTGxGZl/tEi7cnSKyjgXfCIc2J7ljIxHFdu3+qOOZ/PoS9hbq4oWjeLCD9qv6s/G3fUhLfuLq7lG5DYa6InBqjRj056eAyIf87qNIW8DhgM0pIsZiOMUde1QR
  template:
    metadata:
      creationTimestamp: null
      name: values-secret
      namespace: traefik
