apiVersion: v1
data:
  values.yaml: c2VydmljZToKICBzcGVjOgogICAgbG9hZEJhbGFuY2VySVA6IDE5Mi4xNjguMi4xMCAjIHRoaXMgc2hvdWxkIGJlIGFuIElQIGluIHRoZSBNZXRhbExCIHJhbmdlCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: values-secret
