apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rest-api-ingress
  namespace: cockroachdb
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`db.{{ .Values.cloudflare_zone }}`)
      kind: Rule
      middlewares:
        - name: restapi-basicauth
          namespace: cockroachdb
      services:
        - name: rest-api-service
          port: 8010
  tls:
    secretName: {{ .Values.cloudflare_zone_hyphen }}-tls

