statefulset:
  resources:
    limits:
      cpu: "1500m"
      memory: "2Gi"
    requests:
      cpu: "1500m"
      memory: "2Gi"

storage:
  persistentVolume:
    size: 10Gi
    storageClass: "longhorn"

