apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-server-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

