---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgA0nokvG03zBzXCh7AaDZKd/j4Oilg0buHvINfH5HkbLR/KKd7koVMGI/np1Ro9dx0odyk5xvvrFB1Pu351vc/zhjoRVqSSu1uSBYHOCN5YcjEimOroO1bmj+Yv7wIAjJLkV+A0f7NnRfMVB906ymgCEjLcVLxZZdNuRwZ24oGDos3+E9u64dxqLaieQvOU8xuh7X8ivdC64YIk7sY3axZDlQPxVHEdKoEBx1gBYgQbPWxAq1f6hIy+GCASd52Q20d124PIL5/ZxoN2KIyi5Zh8Xq3lW4xNRaBFVq5rtgzBMvOz4EU81EHpfTWSW5wgLsLFqdwNu/iCg7BbSeaxSsXhfYnqhMiRN+AewWWO/zzfIsfbKNe0UrGLI4m5BbeEeXK9G5wlLBzd7z2CGF0Bw3Yti7aim8hlxEBZjJ0EuVhZomg8V7foMW2Um+qROAxSzaTN3LDgPBnzpfkwJTXcpo1Vv/FXqklMFwq5ISERvCGCEqj2/EDEYNXbaECgjNSlivwM9J2F0vz3txXU7Sx8B+3lyoi2ww+wp/Yist20VG76vtT8ef3AlXiKpV8/Mj7+YE14mMjlnovE4+8QWkOR77GhhL7L4fyiDVABFfzppu1wzkALrdL7+3euFgHvHLnmYdDvTvIWNQTcLiy7YKlQVzPpqjGmqy675xq8/VsmN1aOnggeY2bqKiojuRwd3ma51zbd3oBuqxLilcGCo/NI0C/rhAZXlg==
    CIFS_USERNAME: AgBYt5OqqeENdhy10uG+fz2t3Lf/35F+1UWqsmk6GZ1TMFpKX/y98fWbVtK0V6RDO2wxPAvUlOYW3hlReaLZBr+LIerl+XJVWIRdmH6Zib4D+RfDoRM8EBrzLGQt20IJRzbN3faTyg84EOP2px42fda4VlZELG531+9gmfC017bClva5Y5POgiUti9Feqt1voO1EPxINJH2nmJpqKQiOuwG6Rk1kegSJnBCtZGk+jZTLig6SjHPHeIu2tIKBNfB2hJI28qTNFw8vfgxEFkVi5lmX6Vjdo3oZcthjA06uSDVOytM3SL88O1pGHTz71H7AtDhyfxu/1audUlAy5qkriY2NBLXOVVUdZmUlHjOV5ebRV9lPPVfh+x4UsuS0QElRgjaK+hlhSSPHvkvAVS3BXqwVELjKvjW6Vv1g5E3+1gWU95eCPZAIGXO5bkjMcfvAkEBjY+swoGLtbNk24g2js3DlN2wVchiyO4F0j0c31n9Ud53QR9fP++rH3XuwU7S0CNm0GHcmgfaXgDuluEhze8V6tRYs+xdXzAK7OPOqfRR9l177PX2b9NJc6PqfpXtfzCDbI4cH24z1RFoY70Yv8jWJ7rA6QksCJ+lqmtbVVb4nx0F3qNPqS9b8tqb1u+tL+iSxkVVNX7dIwLK/2uxT/6v783kqspOZYuFW/FRK4QT7DuCs6QRvkgBXuiBzq6l3PAjhA12wslY=
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
