defaultNamespace: traefik
#namespace: traefik

labels:
  app: traefik

helm:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  version: "37.1.1"  # You might want to specify a specific version instead of using "latest"
  valuesFiles:
    - values.yaml  # Make sure the file name matches exactly what you have
  releaseName: traefik
  valuesFrom:
  - secretKeyRef:
      name: values-secret
      namespace: traefik
      key: values.yaml

kustomize:
  # To use a kustomization.yaml different from the one in the root folder
  dir: ""

# Optional: Configuration if you need to apply specific labels or annotations to the namespace
namespaceLabels:
  managed-by: Fleet
namespaceAnnotations:
  fleet.cattle.io/managed: "true"

# Optional: You might want to pause the rollout to manually inspect before deployment
paused: false

# Deployment strategy can be configured if needed (for larger or more complex deployments)
rolloutStrategy:
  maxUnavailable: 10%

dependsOn:
  - selector:
    matchLabels:
      app: cert-manager-prep
  - selector:
    matchLabels:
      app: secrets
