globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    tls:
      enabled: true
    # forwardedHeaders:
    #   trustedIPs:
    #     - 10.42.0.0/16
    #   insecure: false
  traefik:
    expose:
      default: false
      internal: true
  pms:
    expose:
      default: true
      internal: false
    port: 32400
    exposedPort: 32400
  wireguard:
    enabled: true
    expose:
      default: true
      internal: false
    port: 51820
    protocol: UDP
    exposedPort: 51820
      
ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

experimental:
  plugins:
    traefik-plugin-rewrite-headers:
      moduleName: "github.com/XciD/traefik-plugin-rewrite-headers"
      version: "v0.0.4"
    traefik-real-ip:
      moduleName: "github.com/soulbalz/traefik-real-ip"
      version: "v1.0.3"

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  loadBalancerSourceRanges: []
  externalIPs: []
  additionalServices:
    internal:
      single: true
      type: ClusterIP
      labels:
        traefik-service-label: internal
