---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard
  namespace: wireguard
spec:
  encryptedData:
    wg0.conf.template: AgANsT6dfDnZgJ/TSSjWyjyS+CFnQD1NEgOraGiaoD6vwQ/1gVJx8TuGlX2l47XCIQexpJmFOAoInV59SCQ5KAybBTh6+qb6lRWDQVDTCUVdGO6Wy/E2Tez2lf2m8NjQzFDu9OTIr3kgXQnreboTyxQHoX2ZJq0tSh6nySne74wUOImrgY0eincO3qRXyMmpwkzvuxyZFtbhvehmVpqXT0qn3NlxaQXQ9EqkKyO3oCYjCwmEobCn35RcdNem7rqQC326g6xyhv0IbG3leaQyFuUONIUuTCxBKqNJkGjNJ48ll4Pw7CPmP0yVcgZvGt53rtUs3sRC0MxhFKjMOw2mbFQb/WUrxRmaMs01DeFa4GB1Viikf/nGb5g5fMhKFPgDeaJVkGF8p9nufTUGkOZp+PhFu0hCswv4u7pPP4pJlRsUc9Cm1rW5AQ62fpzXtWomLe9L+afvUI03gDXSfJQ7lBv+mniuCDlrN3mZVUZlau7g1woKPsTi3+sa3FyZdHDMEtz5UPebMxuwhVuQsyFxjIUFOEzoEzCL/mqPMiilW0FUeGlJmKeig3ero/rJGQWkDwmLimmtkwLqkw+q7StYPId4Hj6XYR/pLyD75XCm+J1YUsVyf0D97HfmNklW6CGwxv6XiYP6pk3FaUicT3q3EqUiCLH3sizfT8/X06IL1O1dtL0XcybC6WYcSf87By+8iBv42nJyTYTNF6QETeAaSug5vvmmFw/aZdYKd6mFc4lgLkdWb8BG2OPUMJev43sucQzylhsyNLf97Y7yeVw7bCJW4FXCSiB1TUjGNOqm/6AOB/8IQnqTcfsmbTBxbjxXg/MlRjd1NmRXmAg3arK76UYu9iQrXVGP0GEljPoYnPYiXEpyDAu8mulbdum1lfEwUBuYqNmFpkVbeQ9jzzW8va5RnI0mxthAjxoBsOvy372j7DnVyfPQOUODLKJGK9DjHrUMBhIODhs5+1hGORSh+jrg3TnEDRBq318X9a4yXaNdu/74rxZIwyyE0Trh96SE0/z2KMe5dnduHNZpKx7vf+XkjAR9N8JBkF878HP4+0CmKtcB+v6b3YQYzFchKj2LW4ubi9tX+AJcpAZIQQsEhIcOF4A8z+EScGfZofQTp/LG/aa+YfBsbjZTEUe01GwDftkhevWT423sEqPYEVzsPYfMvQL1Sw/cFipyCVp8fC3sY/sakirVTx/k8wwlUPnLbXeVS0Ea+LOod/a3J/VIafS0l1EcpwrWzDQUaD/9ic9H9ujBeVwe6xfxRnwWfMA0KFUIFCaGURgfkHRuiHQ43JTTI1T12RW/LNzACupnDLyQFwQFXZA6Mc6jHP8S9y7g+ssa1l0c/+ZD6hbqL6sKUg==
  template:
    metadata:
      creationTimestamp: null
      name: wireguard
      namespace: wireguard
    type: Opaque
