---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pinchflat-secrets
  namespace: media-server
spec:
  encryptedData:
    auth-password: AgA/CwGd6JfEoxalM0LpX5VrH4B1rdvF/DIjXeypDLPvi+/HOqE/NWJwImpcUrxpRlD2pG5tEcAb4N3s0IWPH7V8GI+FlQncPYbKE+jkuAckvDpLPv9zn0qyxbTVdhWBohWGozCz2osdmmPPVAXAiDX25GKY60TeFMqw3/LGC/mjr/LFu88M4APsPvnuUVcBH/nTLYCBwqYOoUhPT0xo9BCh1nARGAOct0ffHrHyoeA66k5GMUBWvSjqphYQ97GvQ/GamhoNJjheJ/LwF6MuPHypcI6DBSm8/Pyejq4dHs0r0//AofnGJD1U9CkZezVampRK0XG3qOXPUujBWHRGehXgGoSZkKLg7UGXIFzKZOGL3WxeVSOzgns7hQYGnnlK1BW54/080zrCWiinPNmsos/xslvBeURqKiPeomntEdlRTsvjoF5v5CbVrucPIApesnPczMnpcPIqRnfFdfvWKhThs//xjRxghaTUDzGH4Rz9rxO4B/f/Ht0h2rMcFhkmMwnb9eL8RgpGACHiu+fHNaSVemBlAGw+HKW+tl153QGc9THAq1oKrbFZ1DoM+oVs+nUtWqOL/tWD2iTR6wjH6AJZpMSfQopY0ziJNc5JE2PZuGZVk9ajjhWulxainCTtuLphmGkVt5S9+dR3NPHXL/35u94q7PFNggYivx7npWCLIps7dxQsylEiLXzEPj/7Ocpxq0jbnJYaYk9R+VntNF06PXUmAJiRPfVmoQ==
    auth-username: AgBdlAUZXf4J93sEKgKVXVZex9emQNUCs5i71CFnBl2T9dQT/4aAfbVGV1S09WOGtmlK4JlRa+kBLFpOzTumCTThr7y9b29hzbtUVsw8v2yzpC0WbyPQhhhWYZJ5euNp44+zFKRurSRHwDc7lQ0pf+/kq8JdYgU4c+d4XkTiCdt8xyb5hhMGlmxxL8wmZVsnb4QXDDYVrO9e6B47orwKpM8tHvJxv5KSG0d6rT4a1f7sj7BQ/JOk7bqDtAKKoDeUVdzV/I2xWpXpLHTQcmyXTGmNZT+TVOCt+9jSvB7EKLwNJqaBBC/uUMSrS27ID8hptKrP5/7GB05afttagYtbD17KGN/78DRt8SgS9D8dV4a1fnqS/H7zJzyxITQuDoshQFtR+0AeZj83tU1zY/sIVil9U/JXC9oPQqkq1dLs+qa9iOtO2ElVvEu/6vFeNy54gQ0liifuGeSWwsh0h7meWZ5BYvZgVdXk6Tf9wEXdRtJ9THsJY2a/26cwnD+EWA4OOP21/y9dofO8bgZtX5Rg78GAHReeUnZN7aFG/MpBn6ktst2+xbXP52hnpYeUybTpfO23HSPSHAe7+elqXN5f0Cg8WoST7Btt+F1S197pegdI/ZbLPo7foT5wEcg4ixCmQXG8UlCNbbH9bO87/EV/rJIDsgd8bLglomvSvemigzPGrKmi8ch20RhQK+7xyrqGiJ9VG+5duA==
  template:
    metadata:
      creationTimestamp: null
      name: pinchflat-secrets
      namespace: media-server
    type: Opaque
