prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: true
    podMonitorSelectorNilUsesHelmValues: true

grafana:
  # Information in SealSecrets
  # admin : "admin"
  # adminPassword: "adminPassword"

  sidecar:
    dashboards:
      enabled: true

    datasources:
      enabled: true
      # url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
      # timeout: 30
      defaultDatasourceScrapeInterval: 15s
