prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: true
    podMonitorSelectorNilUsesHelmValues: true
    scrapeInterval: "30s"
    evaluationInterval: "30s"

grafana:
  # Information in SealSecrets
  # admin : "admin"
  # adminPassword: "adminPassword"

  sidecar:
    dashboards:
      enabled: true

    datasources:
      enabled: true

  env:
    GF_RENDERING_SERVER_URL: http://grafana-image-renderer.monitoring.svc.cluster.local:8081/render
    GF_RENDERING_CALLBACK_URL: http://monitoring-grafana.monitoring.svc.cluster.local:80/
    GF_LOG_FILTERS: rendering:debug

  persistence:
    enabled: true
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 5Gi
