prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: true
    podMonitorSelectorNilUsesHelmValues: true
  prometheusSpec:
    scrapeInterval: "30s"
    evaluationInterval: "30s"

# prometheusOperator:
  # serviceMonitor:
  #   interval: "30s"
  #   scrapeTimeout: "30s"

grafana:
  # Information in SealSecrets
  # admin : "admin"
  # adminPassword: "adminPassword"

  sidecar:
    dashboards:
      enabled: true

    datasources:
      enabled: true
      # url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
      # timeout: 30
      # defaultDatasourceScrapeInterval: 15s
