prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

grafana:
  # Information in SealSecrets
  # admin : "admin"
  # adminPassword: "adminPassword"

  sidecar:
    dashboards:
      enabled: true

  service:
    type: ClusterIP

  defaultDatasourceEnabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
          # isDefault: true

